### ISSUE TITLE
Yoast is incompatible with EXT:vhs AssetService

### ISSUE THREAD

**Issue by dr-bock** [Yoast/Yoast-SEO-for-TYPO3#104]
Decide you, if it's only an info or a bug-report:

If you use the AssetService (by using the asset.style ViewHelper) from EXT:vhs to generate/concat your Stylesheets, the Yoast Preview XML becomes invalid. The AssetService places the Stylesheet before the xml-declaration:

```xml
<link rel="stylesheet" href="/typo3temp/vhs-assets-4e9f38df736e629d6bb6a16ac0dbb5c0.css?1506804614" />
<?xml version="1.0" encoding="UTF-8"?><preview><meta><url>https://mydomain/test</url>
...
```

The AssetService wants to place the Stylesheets before the closing-head-tag or if the service does not find the tag, at the beginning of the document.

Workaround for us was to place a "fake-head and -body" in the xml:

```
yoast_seo_preview {
    admPanel = 0
    40 = TEXT
    40.value = <head></head><body></body>
    40.wrap = <vhsassets><![CDATA[|]]></vhsassets>
}
```
So you get this xml:

```xml
<?xml version="1.0" encoding="UTF-8"?><preview><meta><url>https://mydomain/test</url>
...
<vhsassets>
<![CDATA[
<head><link rel="stylesheet" href="/typo3temp/vhs-assets-4e9f38df736e629d6bb6a16ac0dbb5c0.css?1506805604" /> </head><body> </body>
]]>
</vhsassets>
</preview>
```

You must also set admPanel to 0, because TYPO3 renders AdminPanel Scripts, if there is body/head in document.

**Comment by haassie** [comment]
I don't have experience with VHS, but isn't it possible to exclude the AssetService for specific page types? It is a XML and doesn't need a stylesheet at all.

**Comment by dr-bock** [comment]
I don't know any Config-Param for that. I was just as surprised about the behavior of vhs. I think the problem is when you use the vhs-ViewHelper to generate Stylesheets. These are of course executed when rendering the ContentElements. And normally you don't render complete ContentElements in an xml. In most cases, simple DB-fields like bodytext, header etc. are used to generate a xml over typoscript or over an ExtbaseController.

The stylesheets we added by vhs-TypoScript Settings are ignored.

Of course, we could wrap the vhs-viewhelpers with a condition to the pagetype or extend the viewhelper-class to add a pagetype-condition. But this is of course slightly more complicated. :) So, not a big problem for most developers and maybe a feature request for vhs rather than a bug-report here.

**Comment by haassie** [comment]
I did some research and now, I get your point. I think this is a feature request on VHS indeed because when you want other views as HTML, you don't want stylesheets at all or maybe even when you do a print version of your content. Maybe there is already a solution for this, but as said earlier: I never used VHS, so I don't know all the ins and outs.

If you are ok with this, I will close this issue. If it seems an issue with the Yoast plugin, we will reopen this issue.
