### ISSUE TITLE
saving of images discards other changes

### ISSUE THREAD

**Issue by dieMelanie** [Yoast/Yoast-SEO-for-TYPO3#106]
If you have unsaved changes in the yoast module and safe after uploading a social share image the other changes (title, facebook description) are discarded and lost.

It seems hitting the safe button when there is an unsaved image  only saves  the image information and nothing else.

**Comment by haassie** [comment]
I will investigate and if I can reproduce, I will fix the problem. If not, I will come back to you for some more information.
