### ISSUE TITLE
Overwrite Title and OG-Tags from Extension

### ISSUE THREAD

**Issue by mpruy** [Yoast/Yoast-SEO-for-TYPO3#110]
Is it possible to overwrite the Title and OG-Tags from an own Extension? I have Database-Records, which should have other Title than the Page, but when I work with additionalHeaderData, I get duplicated Tags.

**Comment by dr-bock** [comment]
You can overwrite the default YOAST-templates and set there different conditions to play out the MetaTags or you can get the MetaTag data directly from the data of your extension.

We work there with a mixture of different ViewHelpers and variables passed to the YOAST templates via TypoScript.

**Comment by mpruy** [comment]
Are there any examples to get the MetaTag-Data directly from my extension-data?? Unfortunately the Docs dont handle something like that. :(

**Comment by haassie** [comment]
We can add an example in the documentation. @dr-bock is this something you can and want to do?

**Comment by dr-bock** [comment]
Maybe I will find some time at the weekend. Currently, my working day is pretty full.

**Comment by haassie** [comment]
Would be great! If you don't have time, no problem. I can do it in the somewhere in the upcoming weeks.

**Comment by haassie** [comment]
In version 2 this will be easier. When releasing version 2 I will add it to the manual how to override fields. Also examples how to integrate with extension will be available.
