### ISSUE TITLE
Data not saved when accessing via menu point: WEB > Yoast SEO

### ISSUE THREAD

**Issue by berthgithub** [Yoast/Yoast-SEO-for-TYPO3#111]
Hey there,
there is a bug? in Ext. yoast_seo | 1.2.3. used with TYPO3 CMS V. 7.6.23, 
If I access the YoastSEO extension via the main menu WEB > Yoast SEO, then the data in the form get not saved. Via WEB > Page all fields get saved.

But anyhow thanks a lot for bringing Yoast-SEO to TYPO3!

Regards, B

**Comment by haassie** [comment]
Hi @berthgithub. Thanks a lot. In the Web > Yoast SEO plugin, what do you change? In fact when you edit the properties in Web > Page you are using the same plugin, but it can be a little different in how you reach the module.

Do you have this problem each time you want to save the record in the Yoast backend module? Is it all fields that can't be saved?

**Comment by berthgithub** [comment]
Hi haassie,
I tried title and description, both are not stored. In fact a customer of mine brought the subject to me - therefore I tried it and got the same result.

**Comment by haassie** [comment]
Hi @berthgithub I can't reproduce your issue. I just installed Yoast SEO v 1.2.3 in a fresh TYPO3 CMS 7.6.23 installation and it works out of the box on both ways. Is it possible to create a screenrecording?

**Comment by berthgithub** [comment]
Hi haassie, no idea why, but I can't reproduce the error anymore. Thanks for looking in to this.
