### ISSUE TITLE
add the possibility to override the whole page title (including prefix and suffix)

### ISSUE THREAD

**Issue by bernhardberger** [Yoast/Yoast-SEO-for-TYPO3#123]
Please make it possible to override the whole page title (including prefix and suffix)

**Comment by haassie** [comment]
In v2 this will be easily possible to override the `lib.yoastSEO.pageTitleComplete` TypoScript variable. In v1, you can do it by overriding the Title partial.

If you need any help, please ask in the Slack channel. More than happy to help.
