### ISSUE TITLE
Make the slug option optional.

### ISSUE THREAD

**Issue by hkremer** [Yoast/Yoast-SEO-for-TYPO3#131]
Enhancement request to make the slug option optional. We like to disable this feature because we have a special SEO friendly fixed url structure and we don't like this to be alterd by the slug option.

**Comment by haassie** [comment]
This is fixed with commit f411aa35ab2117c3f617b73b6092b32b9870aa33. Because this is a breaking change, it will be released in version 2 of the plugin. We expect version 2 te be released in Q1 2018.
