### ISSUE TITLE
Analysis does not see page properties media image

### ISSUE THREAD

**Issue by hkremer** [Yoast/Yoast-SEO-for-TYPO3#134]
The analysis reports 'No images appear in this page, consider adding some as appropriate.' although there is an image on the page added via page propreties. It only sees images added via content elements.

The HTML where it goes wrong looks like this:

```
<body class="eo-Site">

<div id="fb-root"></div>

<div class="eo-Site-content">
    <header class="bb-Hero">
        <div class="bb-Hero-container eo-Container">
            <div class="bb-Hero-figure u-l-size1of2 u-xl-size2of3">
                <img class="bb-Hero-figureImage" src="/fileadmin/bestanden-2016/_processed_/b/5/csm_dans-koninklijk-paar_059ea417f2.jpg" width="800" height="450" alt="" />
            </div>
            <div class="bb-Hero-content u-l-size1of2 u-xl-size1of3">

            </div>
        </div>
    </header>
```

**Comment by haassie** [comment]
This is because only the content elements are rendered in the preview now. I will put it on the list for version 2.0 to check if we can easily check the complete page with also information from the page template.

**Comment by RinyVT** [comment]
I'm going to close this issue, since full page analysis is now supported which fixes this issue.
