### ISSUE TITLE
Wrong canonical tag on Homepage

### ISSUE THREAD

**Issue by SOFTWORK** [Yoast/Yoast-SEO-for-TYPO3#136]
I have a problem with the canonical tag on the root url, the plugin give http://domin.xy/homepage/ - but I want to have only http://domin.xy/ in the generated canonical tag. What can I do?

Many thanks.

**Comment by haassie** [comment]
Hi @SOFTWORK. I think this is due to your site setup / realurl configuration. The Yoast plugin just creates a "link" to the current page and is nothing else than what would happen if you put a link to that page in your text. I think you have a rootpage that is a shortcut to the first subpage?

**Comment by haassie** [comment]
As far as I can see this isn't an issue in the Yoast plugin and because we didn't get a reply, I will close the issue. If this issue still happens, please reopen this issue.
