### ISSUE TITLE
Canonical URL without HTTP(s):// gives wrong canonical url

### ISSUE THREAD

**Issue by KoenWouters** [Yoast/Yoast-SEO-for-TYPO3#137]
When i fill in "google.com" at canonical url this URL is not valid and wont be shown in the frontend. When i fill in "www.google.com" at canonical url this URL is not valid and wont be shown in the frontend. 
When i fill in "http://google.com" at canonical url this URL is valid and will be shown in the frontend.

**Comment by haassie** [comment]
This is fixed in version 2.
