### ISSUE TITLE
titleAppend gets added to title after saving

### ISSUE THREAD

**Issue by robinkl** [Yoast/Yoast-SEO-for-TYPO3#139]
I use the titleAppend constant to add the website name to the title.
But after saving the SEO-titel in the snippit, the titleAppend value gets added to the title field.

example: "pagename | websitename", and after saving the snippit; "pagename | websitename | websitename"

**Comment by haassie** [comment]
Thnx Robin. Just released v1.4.1 that fixes this problem.
