### ISSUE TITLE
V2 backend error if tx_news is not installed

### ISSUE THREAD

**Issue by stefanvar** [Yoast/Yoast-SEO-for-TYPO3#143]
I installed v2.0-beta on a local system via composer without news extension and got an error in my backend.
After switching to version 1.4.1 everything works fine again.

![error](https://user-images.githubusercontent.com/8425143/35336329-5a03a5ae-0118-11e8-84d6-f199f579efec.png)

**Comment by haassie** [comment]
Where exactly do you get this error @stefanvar ? I can't reproduce it.

**Comment by stefanvar** [comment]
After I update from 1.4 to 2.0, doing all DB updates without tx_news_domain_model_news and tx_cal_event (both extensions not installed) and clearing the caches. If I switch to "list"-modul I get the error.
