### ISSUE TITLE
Description field fallback and exotic text formatting.

### ISSUE THREAD

**Issue by mdejong1987** [Yoast/Yoast-SEO-for-TYPO3#144]
**Problem 1:**
When there is content on the page that is not UTF-8 the yoast backend element wil show an error like:

`We got an error 200 (OK) when requesting [ website url ] to analyse your content. Please check your javascript console for more information.`

When inspecting in the console I found this error:

`This page contains the following errors:
error on line 1 at column 1859: Input is not proper UTF-8, indicate encoding !
Bytes: 0x0C 0x3C 0x2F 0x70 Below is a rendering of the page up to the first error.`

When removing this formatted text it works fine.

**Problem 2:**
No real fallback for the description field. We had this page with one element on it, more image then text. The yoast backend element wil display an error. When adding a text content element with text it works again or if adding a description in the page properties it works fine.

Also when adding an element with not much text de oops error will still show. So you also need enough text in the element.

Maybe something to look into?

**Comment by haassie** [comment]
Problem 2 is more an integration issue. When no content is entered, it will fall back to a placeholder. A tip when having this kind of issues is to take a look at the normal page and then try to view it in frontend with &type=1480321830.

**Comment by RinyVT** [comment]
Closing this issue due to the age of the issue. Since then the content-analysis has been changed quite much.
Feel free to open a new issue if this is still present in the current 8.0 version
