### ISSUE TITLE
Snippet preview doesn't fall back to page title after editing the "seo title" field

### ISSUE THREAD

**Issue by twllndr** [Yoast/Yoast-SEO-for-TYPO3#147]
If I have not explicitly set a "seotitle", the title of the page is shown in the snippet preview - in my case "Startseite".

![bildschirmfoto 2018-02-01 um 11 32 45](https://user-images.githubusercontent.com/63435/35674054-b7b22370-0743-11e8-85fa-e2e9ff74b492.png)

After adding a custom title it is shown in the snippet preview.

![bildschirmfoto 2018-02-01 um 11 33 00](https://user-images.githubusercontent.com/63435/35674059-bb7a7340-0743-11e8-940c-6903f2fd6e1f.png)

When I remove this custom title it doesn't fall back to the page title I had at first, but shows "Please provide an SEO title by editing the snippet below.".

![bildschirmfoto 2018-02-01 um 11 33 08](https://user-images.githubusercontent.com/63435/35674061-bded381a-0743-11e8-8be9-36ec25d111f0.png)

Why doesn't it just display "Startseite" again?

**Comment by twllndr** [comment]
After posting the images I see now, that on the first image there is an orange bar below the input field for seo title and on the last image this bar is green - although the content in this field is the same.

**Comment by haassie** [comment]
Did you save the page after removing the SEO title?

**Comment by twllndr** [comment]
No I didn't save the page. And I think I don't have to, as the fallback title is already displayed in the seo title field as placeholder. I just want it to be displayed again in the snippet preview, as it did when opening the page properties.
