### ISSUE TITLE
Backend-Module needs Update

### ISSUE THREAD

**Issue by stefanvar** [Yoast/Yoast-SEO-for-TYPO3#150]
Hi,
the backend module needs an update.
![bildschirmfoto 2018-02-12 um 09 19 01](https://user-images.githubusercontent.com/8425143/36088515-df594ea2-0fd7-11e8-856d-b6c41b6a9971.png)
![bildschirmfoto 2018-02-12 um 09 19 08](https://user-images.githubusercontent.com/8425143/36088516-df6f4c52-0fd7-11e8-8138-0155f5fba0a0.png)

But there is no chance to update anything.

Removed, reinstalled, cache cleared.

When I try to deinstall and install again via ExtManager I got the following error
![bildschirmfoto 2018-02-12 um 09 33 28](https://user-images.githubusercontent.com/8425143/36088503-d75d71ec-0fd7-11e8-9f2d-7799f1107f2e.png)

Any idea?

We use dev-2.0-tca 8e2149f

**Comment by haassie** [comment]
Hi @stefanvar can you try dev-master? There is already some rework done in this.

**Comment by stefanvar** [comment]
Still needs an update.
But errors are gone.
How to update? (database analyzer or upgrade wizard is nothing to update)

![bildschirmfoto 2018-02-12 um 09 50 00](https://user-images.githubusercontent.com/8425143/36089079-618951a4-0fda-11e8-83e5-dc7b7ab73c3f.png)
![bildschirmfoto 2018-02-12 um 09 49 38](https://user-images.githubusercontent.com/8425143/36089088-6613ed56-0fda-11e8-9541-516f30a196b5.png)

thanks

**Comment by haassie** [comment]
Do you get the message in the page module but doesn't get an update in the backend module? How do you "know" it needs an update?

**Comment by stefanvar** [comment]
normally there was instead of 'update' an 'analyze'-button
or is the analyze-button gone in the new version and everything is done via the page-settings?!

**Comment by haassie** [comment]
Ah you want to analyse your page? That is now only in page module. Maybe I have to make that a little bit clearer in the backend. All analysis are migrated to the page records.

**Comment by haassie** [comment]
In version 2 the database fields are changed a little bit. Therefore I created an update script so no information is lost. Thats the update module in the backend.

**Comment by stefanvar** [comment]
Ok, then it seems, like there is no error anymore.

**Comment by stefanvar** [comment]
thanks for your support
