### ISSUE TITLE
Snippet preview of hidden news for not admins

### ISSUE THREAD

**Issue by stefanvar** [Yoast/Yoast-SEO-for-TYPO3#151]
If we try to analyze news-records which are hidden, we can do this as an admin, but as a normal user with rights to news-ext and yoast-ext there is a 404 message:

> We got an error 404 (error) when requesting (...)

In the usergroup settings we activated the following settings

![bildschirmfoto 2018-02-12 um 10 29 36](https://user-images.githubusercontent.com/8425143/36090210-c9efcf2a-0fdf-11e8-8eac-3084185d3599.png)
![bildschirmfoto 2018-02-12 um 10 29 52](https://user-images.githubusercontent.com/8425143/36090211-ca088a24-0fdf-11e8-8fa0-0c3ee9826c79.png)

any idea?
thanks

**Comment by haassie** [comment]
Can they see the news records in frontend? You have configured the preview link? If they choose save + view on a news-record. Do they get the news record?

**Comment by stefanvar** [comment]
sorry, I think it was my mistake.
one usergroup was allowed to view hidden preview and the other not.

**Comment by haassie** [comment]
No problem!
