### ISSUE TITLE
Missing CSS in preview snippet

### ISSUE THREAD

**Issue by codemonkey1988** [Yoast/Yoast-SEO-for-TYPO3#152]
TYPO3: 8.7.10 (using composer mode)
yoast_seo: 2.0.0

When TYPO3 is installed in a subdirectory, the yoast-seo-tca.min.css can not get fetched.
I get the following message in my error log:
`core: Core: Error handler (BE): PHP Warning: file_get_contents(/my/path/to/document/root/typo3/typo3//subdirectory/typo3conf/ext/yoast_seo/Resources/Public/CSS/yoast-seo-tca.min.css): failed to open stream: No such file or directory in my/path/to/document/root/vendor/typo3/cms/typo3/sysext/core/Classes/Resource/ResourceCompressor.php line 359`

The correct path would be 
`/my/path/to/document/root/typo3/typo3conf/ext/yoast_seo/Resources/Public/CSS/yoast-seo-tca.min.css`

**Comment by haassie** [comment]
Seems to be an issue in the TYPO3 installation and seems not related to the Yoast plugin
