### ISSUE TITLE
Default images in Yoast Seo Setting couldn't be uploaded

### ISSUE THREAD

**Issue by web2date** [Yoast/Yoast-SEO-for-TYPO3#154]
TYPO3 8.7.10 and YOAST SEO 2.0.0

I can't upload default images in Yoast Seo Settings for Twitter & Facebook

**Comment by haassie** [comment]
I can confirm this issue

**Comment by haassie** [comment]
Fixed with commit 72da392070c9b49d47c139a7c72078464dc4bdcf
