### ISSUE TITLE
Optimize the infobox in the page module

### ISSUE THREAD

**Issue by twllndr** [Yoast/Yoast-SEO-for-TYPO3#155]
The new "Yoast Seo" infobox in the page module looks great. But most of the time I would like to have it collapsed. But when re-entering a page, where it is already collapsed, it still shows in big size with the loading indicator at first. Then it gets collapsed again and moved down a little bit for the "readability" and "seo" info.  This is a little bit annoying, since the rest of the page module is jumping around then.

![yoast-seo-header](https://user-images.githubusercontent.com/63435/36266338-7edde03c-1271-11e8-8cd6-96b0cd25fb4f.gif)

Would it be possible to not open the box, when it should be collapsed already? And maybe directly reserve the needed space for the "readability" and "seo" text, so that the page don't jump, when this info pops in.

Furthermore it would be a nice addition, if the yoast seo "bar" would be completely clickable - not just the tiny arrow on the right. So that it's more like a "accordion".

**Comment by haassie** [comment]
In the latest version, the bar snippet preview is slightly altered. You can't collapse it anymore, but you can hide it in your user settings.
