### ISSUE TITLE
Change of size of facebook and Twitter image failed

### ISSUE THREAD

**Issue by web2date** [Yoast/Yoast-SEO-for-TYPO3#156]
TYPO3 CMS 8.7.10 YoastSeo 2.0.0
Changing the size of the processed images accordingly to the new Social Media sizes 2018 via TS the setting fails:

My failed TYPO3 BE Main Template Setup setting:
```
plugin.tx_yoastseo {
   settings {
          og.image.width = 1200c
          og.image.height = 628c
          twitter.image.width = 1200c
          twitter.image.height = 628c
      }
  }
```
**Solution:**
Add constants in Plugin.typoscript:
```
plugin.tx_yoastseo {
   settings {
       og.image.width = {$plugin.tx_yoastseo.og.imageWidth}
       og.image.height = {$plugin.tx_yoastseo.og.imageHeight}
       twitter.image.width = {$plugin.tx_yoastseo.twitter.imageWidth}
       twitter.image.height = {$plugin.tx_yoastseo.twitter.imageHeight}
…
```
change constants.txt to:
```
plugin.tx_yoastseo {
    titleField = seo_title
    descriptionField = description
    canonicalTagField = canonical_url
    noIndexField = no_index
    noFollowField = no_follow
    titlePrepend =
    titleAppend =

    og {
        titleField = og_title
        descriptionField = og_description
        imageField = og_image
        imageWidth = 640c
        imageHeight = 480c

        fbAdmins =
        fbAppId =
    }

    twitter {
        titleField = twitter_title
        descriptionField = twitter_description
        imageField = twitter_image
        imageWidth = 640c
        imageHeight = 480c

        imageMaxWidth =
        site =
    }
}
```
so its possible to change the sizes via constants successfully 

My working TYPO3 BE Main Template Constants setting:
```
plugin.tx_yoastseo {
           og.imageWidth = 1200c
           og.imageHeight = 628c
           twitter.imageWidth = 1200c
           twitter.imageHeight = 628c
   }
```

**Comment by haassie** [comment]
Fixed with a7cbb96dfa7fdc1dbd9c5d4461ca143fe8488ca0

**Comment by olivermeckel** [comment]
Again not working in 4.1.0?
Width and Height is ignored and image is cropped in height.

Can i disable og and twitter handling?

**Comment by haassie** [comment]
Version 4.1.0 is used for CMS9. In CMS9 the facebook and twitter images are handled by core. So if that is not working for you, can you please create a ticket of forge.typo3.org for this and set the category to SEO?

**Comment by olivermeckel** [comment]
OK, that's why i couldn't find any setting in the plugin ;-)
Maybe you should update the manual:
https://docs.typo3.org/typo3cms/extensions/yoast_seo/Configuration/Social/Index.html
