### ISSUE TITLE
Disabling Yoast on specific page types does not work

### ISSUE THREAD

**Issue by saitho** [Yoast/Yoast-SEO-for-TYPO3#158]
## System information

* TYPO3 8.7.8 LTS
* Yoast for TYPO3 v1.4.1
* (PHP 7.0.22)

## Problem

I have a pageType where I do not want to use Yoast. Deactivating it in the global configuration works:
`config.yoast_seo.enabled = 0`

However deactivating Yoast inside a PAGE object's config options (as stated in the documentation) does not work:
(Example derived from documentation: Disable rendering Yoast SEO meta tags on specific page types)
```
printPage = PAGE
printPage {
  typeNum = 12345
  config {
    yoast_seo.enabled = 0
  }
}
```

## Expected behaviour

The Yoast Metadata should not show on frontend sites called with a special page type that disables Yoast.

## Possible Solution
Yoast's PageMetaRenderer gets the configuration from `$config['config.']['yoast_seo.']['enabled']` (dissolving $config that gives: `$GLOBALS['TSFE']->tmpl->setup['config.']['yoast_seo.']['enabled']`).
I compared that to how the TYPO3 core accesses the configuration and they are using `$GLOBALS['TSFE']->config['config']`. In this case I looked at the setting "htmlTag_setParams" inside the PageGenerator which is working both ways (globally and type specific).

So I replaced `$config['config.']['yoast_seo.']['enabled']` with`$GLOBALS['TSFE']->config['config']['yoast_seo.']['enabled']` and got it working globally and type specific. :)

This is still the case in the code of PageMetaRenderer on current master branch. (Haven't tested it in TYPO3 though)

**Comment by haassie** [comment]
Thanks for the report! The proposed solution is working indeed!
