### ISSUE TITLE
Found a error while creating a new Alternative Page Language

### ISSUE THREAD

**Issue by rickone1** [Yoast/Yoast-SEO-for-TYPO3#165]
If you're creating a new Alternative Page Language the $uid is null because it doesn't exist yet and so your function will break and you're not able to create new alternative page languages.

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/7e2e89881334c76caa90a079de51ece9a49d86f9/Classes/Utility/YoastUtility.php#L110

**Comment by haassie** [comment]
Thanks @rickone1. Will check this and will make sure the fix is in the release of Friday.

**Comment by rickone1** [comment]
Thanks 👍

**Comment by haassie** [comment]
If you have the possibility to create a patch yourself, we are really open for contributions!

**Comment by haassie** [comment]
Hi @rickone1 do you have an error message? I can't reproduce and even with some theoretical checks, this shouldn't be a problem because the getRecord method itself is checking the a proper uid is given. 

Do you have some more information? So error message, CMS version, Extension version etc?

**Comment by rickone1** [comment]
The error message I got is` #1476107295: PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /var/project/www/typo3conf/ext/yoast_seo/Classes/Utility/YoastUtility.php line 109`

We are currently working with typo3 8.7.10 and Yoast 2.0.2
I've made a screen capture so you can see the issue, https://screencast.com/t/g4WRJzKqBqxe

**Comment by hacksch** [comment]
This issue was solved in #159

**Comment by rickone1** [comment]
I would not fix it like that, Why try to get the record when the uid isn’t set. I would suggest to check if the uid is set then get the record. If it isn’t set then return ‘’;

**Comment by hacksch** [comment]
I agree. Is a better way
