### ISSUE TITLE
Dis-/Enable SERP preview in page module via extConf

### ISSUE THREAD

**Issue by josefglatz** [Yoast/Yoast-SEO-for-TYPO3#171]
In an development environment it's not  useful everytime.

A check via extConf (bool) would be nice. With that's it's possible to dis-/enable via TYPO3_CONTEXT environment variable.

The feature can be extended by adding support for:
- (Page)TSConfig Switch

**Comment by RinyVT** [comment]
Closing this issue, this is possible with:
https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/master/en-us/Configuration/SnippetPreview/Index.html#disable-snippet-preview-with-pagets
We've looked at doing this within the global configuration but the environment checks are also possible with tsconfig.
