### ISSUE TITLE
Fallback og:images don't work on not default languages

### ISSUE THREAD

**Issue by web2date** [Yoast/Yoast-SEO-for-TYPO3#172]
if I set default fallback images at the YOAST SEO settings module these images show up in the default language (DE) but in the additional language there is no og:image at all… (TYPO3 v7.6.25 / Yoast Seo 2.1.0 / single tree / default language DE + EN + IT + NL)

**Comment by typecat** [comment]
I'm using EXT:yoast_seo 2.1.0 on TYPO3 7.6.23 and the fallback images cannot be set at all in the Yoast settings module. If I upload a file and click the save button, the fields are empty again ("None selected").
According to the TypoScript there should be a filed `tx_yoastseo_settings_facebook_image` in the `sys_file_reference` table, but the extension of this table is missing in the `ext_tables.sql`.

**Comment by typecat** [comment]
Can still confirm for EXT:yoast_seo 3.0.2 on TYPO3 7.6.30.

**Comment by RinyVT** [comment]
I'm going to close this issue, `og:image` is being handled within TYPO3 core nowadays.
