### ISSUE TITLE
Snippet preview doesn't work - ssl only on main domain, but not in second pagetree

### ISSUE THREAD

**Issue by twllndr** [Yoast/Yoast-SEO-for-TYPO3#173]
I'm using the TYPO3 backend with https://www.domainA.tld/typo3/ and everything works fine in the pagetree of domainA. But I have a second pagetree, with a domain without ssl and there the snippet preview doesn't work. I get the following error:

`We got an error 0 (error) when requesting https://domainB.tld/index.php?id=605&type=1480321830&L=0 to analyse your content. Please check your javascript console for more information.`

The javascript console says:

`GET https://domainB.tld/index.php?id=605&type=1480321830&L=0 net::ERR_CERT_AUTHORITY_INVALID`

So I think the problem is, that domainB is called with https, as I don't have ssl there.

**Comment by haassie** [comment]
First of all: I think you should make sure your other domain gets a certificate as well. 

That said: Getting the domain to show that page is heavily relying on core features. By default, it will check the environment variable `TYPO3_SSL`. After that, it will check the PageTSConfig for `TCEMAIN.previewDomain`. If the value of that property contains http:// it will use http. 

In your case, I think it should work to set the preview domain in the siteroot of domainB.tld to use http://domainB.tld.

Please let me know, if this works out for you!

**Comment by twllndr** [comment]
Thanks for your feedback. With the preview domain it doesn't work either. It correctly uses http instead of https then, but in the javascript console it shows the following error:

`Mixed Content: The page at 'https://domainA.tld/typo3/index.php?route=%2Fmain&token=3fe57f01d5b771ac04e279' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domainB.tld/index.php?id=605&type=1480321830&L=0'. This request has been blocked; the content must be served over HTTPS.`

So this could only be solved with also using a valid ssl certificate on the second domain for now. As domainB is a test domain it won't get a certificate. When the site goes live with domainC (which has ssl) the problem will be gone. But until then, I have to live with the snippet preview not working.

Final question: Why does it need the frontend at all for the snippet preview? I mean yoast_seo could get the data through the backend directly, no?

**Comment by haassie** [comment]
It should work with self signed certificates or for example let’s encrypt. 

We need the frontend because people can have al kind of alterations in place there. 

But we are working on a new way where the complete page is checked. Although that won’t fix your problem.

For now I will close this issue.
