### ISSUE TITLE
Url in snippet preview has a leading slash ("/") with realurl in multidomain/multilang config

### ISSUE THREAD

**Issue by djangones** [Yoast/Yoast-SEO-for-TYPO3#174]
If realurl is setup with a `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DOMAINS']` encode/decode-configuration , there is always a leading slash prepended to the url, like "/https://www.domain.com/" instead of "https://www.domain.com/".

Additionally, if a realurl pathsement is set in the page properties, only that is used as the snipped url, like "/pathsegment/" instead of "https://www.domain.com/pathsegment/".
A workaround for this behaviour is to clear `lib.yoastSEO.pathOverride >` but that does not fix the leading slash.

If I remove the whole `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DOMAINS']` config array key the snipped urls are shown as expected but this configuration is essentially for a multidomain language setup: https://github.com/dmitryd/typo3-realurl/wiki/Language-Domains

**Comment by RinyVT** [comment]
I'm going to close this issue due to the age. Feel free to open a new issue if there's a problem within the current (8.0) version.
