### ISSUE TITLE
Extension breaks "default" javascript/css behaviour in Page module

### ISSUE THREAD

**Issue by josefglatz** [Yoast/Yoast-SEO-for-TYPO3#175]
# Situation

TYPO3 has some kind of base of Bootstrap CSS and Javascript. I heavily use custom backen previews for content element (via simple backend preview and DrawItem hook). For example the collapse feature is broken when the yoast extension is active.

**Following example doesn't work as expected if the extension is active:**
```html
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:theme="http://typo3.org/ns/JosefGlatz/Theme/ViewHelpers" data-namespace-typo3-fluid="true">

<div class="theme-backendpreview-{CType}">
	<button class="btn btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{uid}"
			aria-expanded="false" aria-controls="collapse{uid}">
		<div class="panel">
			<strong>{header}</strong> <span class="caret"></span>
		</div>
	</button>
	<div class="collapse" id="collapse{uid}">
		<div class="panel" style="padding: 6px;">
			{bodytext -> f:format.stripTags() -> theme:backend.contentEditLink(uid: uid)}
		</div>
	</div>
</div>

</html>

```

# ToDo

Find a way to not break the default behaviour of the backend.

**Comment by haassie** [comment]
Hi @josefglatz . I will try to reproduce this error. A first brief look in the code of the plugin didn't get me any idea. All collapse stuff in the extension is targeted on `.yoast-collapse`.

What exactly is not working? It is not toggling or is the complete button not shown anymore?

**Comment by josefglatz** [comment]
Hey Richard,

I don't use any custom JS in my extension - I just use the mentioned HTML which triggers TYPO3 Core's Bootstrap collapse Javascript plugin.

**Comment by haassie** [comment]
Hi Josef, can you test again with the today released version?

**Comment by RinyVT** [comment]
Closing this issue due to lack of feedback (and the age of the issue). Feel free to open a new issue if it's still a problem.
