### ISSUE TITLE
Strange title when News list view is in the page

### ISSUE THREAD

**Issue by stat1x** [Yoast/Yoast-SEO-for-TYPO3#180]
Hi,

I've got this title in the wonderful yoast_seo module in backend when I have the News list view in the page : 
"This is an example title - edit by clicking here" and I cannot change it.

Is it a normal behavior?

![image](https://user-images.githubusercontent.com/11523234/39173216-5cd43514-47a4-11e8-9477-b667a8d4364f.png)

**Comment by haassie** [comment]
You get this when no title is given by the preview call. Can you send me the output when you visit this page in frontend with the get-param `&type=1480321830`

**Comment by stat1x** [comment]
I have this :

`<preview>
<meta>
<url>http://typo3.local/</url>
<title>
<![CDATA[ Home - Enterprise ]]>
</title>
<pageTitle>
<![CDATA[ Accueil ]]>
</pageTitle>
<pageTitlePrepend>
<![CDATA[ ]]>
</pageTitlePrepend>
<pageTitleAppend>
<![CDATA[ - Enterprise ]]>
</pageTitleAppend>
<description>
<![CDATA[ ]]>
</description>
<locale>fr_CH.utf8</locale>
<slug>/</slug>
<pathOverride/>
</meta>
<content>
<element>
<![CDATA[
<h1 class="">	Nos dernières actualités	</h1>	<div class="news">  <div class="news-list"> <div class="row"> <div class="col-md-4"> <div class="thumbnail"> <div class="article articletype-0"> <div class="no-image"> <a href="/article/news/detail/News/news-1-349844"><span class="fa fa-picture-o" aria-hidden="true"></span></a> </div> <ul class="news-information list-inline"> <li> <time datetime="2018-04-23"> <span class="fa fa-calendar" aria-hidden="true"></span> 23.04.2018 </time> </li> <li> <span class="fa fa-user" aria-hidden="true"></span> par <span>Jérémie Roulin</span> </li> </ul> <h3>News 1</h3> <div class="teaser-text"><p>Ma news 1</p></div> <p><a class="btn btn-default" href="/article/news/detail/News/news-1-349844">Read more</a></p> </div> </div> </div> </div> </div>  </div>
]]>
</element>
</content>
</preview>`

**Comment by RinyVT** [comment]
Closing this issue due to the age of the issue. The content rendering and analyzing has been changed a few versions ago to not work with XML but with the HTML output of the page.
Feel free to open a new issue if this issue still occurs with the new rendering mechanism.
