### ISSUE TITLE
Missing fields breaks migration step

### ISSUE THREAD

**Issue by hacksch** [Yoast/Yoast-SEO-for-TYPO3#182]
TYPO3 8.7.12
PHP 7.1
Yoast 2.1.0 / master

Hello,
when i execute the "Execute database migrations on single rows" task in the Install Tool Upgrade Wizard i get an sql error:

` An exception occurred while executing "UPDATE 'pages' SET 'tx_yoastseo_snippetpreview' = ?, 'tx_yoastseo_readability_analysis' = ?, 'tx_yoastseo_focuskeyword_analysis' = ? WHERE 'uid' = ?" with params [null, null, null, 1]: Unknown column 'tx_yoastseo_snippetpreview' in 'field list' `

The field definitions for "tx_yoastseo_snippetpreview", "tx_yoastseo_focuskeyword_analysis" and "tx_yoastseo_readability_analysis" for the tables pages, pages_language_overlay e.g. in the ext_tables.sql are missing

**Comment by haassie** [comment]
Did you already cleared your cache. Because these fields doesn't need a database field. I have had this issue before (on other extensions) and after clearing system cache everything works fine.
