### ISSUE TITLE
No internal links found, but there are internal links

### ISSUE THREAD

**Issue by Salmonrules** [Yoast/Yoast-SEO-for-TYPO3#189]
# Usefull information
TYPO3 version: 8.7.16
Yoast SEO version: 1.4.1

## Try to achieve
I have a page with some internal links in them. They are linking to existing pages.

## What do we expect?
I expect the message "No internal links appear in this page, consider adding some as appropriate." doesn't show up.

## What is happening now
The message "No internal links appear in this page, consider adding some as appropriate" is showing up. After some debugging I saw that `linkStatistics.internalTotal` was `0`

**Comment by RinyVT** [comment]
We are currently at 2.1.0 where this issue is fixed, please update :)
