### ISSUE TITLE
Do not create table if it doesn't exist

### ISSUE THREAD

**Issue by spoonerWeb** [Yoast/Yoast-SEO-for-TYPO3#193]
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/10deb0e9272c14a14f0bd4a6952bc381cbfdcd1a/ext_tables.sql#L61.
Same for tx_news.

I have an installation running with tx_news and without cal. The table for cal was created although there is none yet.

**Comment by haassie** [comment]
See pull request #190

**Comment by haassie** [comment]
With pr #200 we removed the dependencies on EXT:next and EXT:cal. We will make a major update and will provide developers the code how to implement it for EXT:news.
