### ISSUE TITLE
OpenGraph & Twitter Prepend and Append Title

### ISSUE THREAD

**Issue by runde8** [Yoast/Yoast-SEO-for-TYPO3#198]
Is there any possible way to integrate a og prepend or append title?
Atm. there is just a normal title way but there is no way for the og or twitter title.
smth like that: tx_yoastseo.og.titlePrepend

**Comment by haassie** [comment]
Hi,

To be short: Yes there is!

The rendering of the og tags are based on TypoScript settings. As you can see on https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Configuration/TypoScript/Setup/Lib.typoscript#L129, you can easily add your own wrap around this text. 

If you need any help, you can also ask in our slack channel on typo3.slack.com #yoast-seo-for-typo3

**Comment by shabnamKhan** [comment]
Hi,

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Configuration/TypoScript/Setup/Lib.typoscript#L129,

Link is not working.

**Comment by haassie** [comment]
This is not needed in CMS9 anymore. The extension is refactored now, so if you are using v5+ of the plugin, you can check https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Configuration/TypoScript/Setup/CMS8.typoscript.
