### ISSUE TITLE
Error when creating a page over the context menu

### ISSUE THREAD

**Issue by jagodzinski** [Yoast/Yoast-SEO-for-TYPO3#202]
When I create a new page over the contextmenu (New) in the navigation I get following error:  Attempt to modify record '[No title]' (pages:-66) without permission. Or non-existing page. The error appears after safing the new page.

### Technical info
TYPO3 8.7.17
yoast 2.1.0

**Comment by christianbltr** [comment]
I can confirm this with TYPO3 8.7.18 and YOAST SEO 3.0.3.

**Comment by jagodzinski** [comment]
Hello,

the fix works for me! Thank you!

**Comment by christianbltr** [comment]
Hey,

unfortunately now I get the error

2: SQL error: 'Incorrect integer value: '' for column 'tx_yoastseo_cornerstone' at row 1' 

when I try to create a new page from the context menu. Dragging and dropping a new page from above the page tree still works.
