### ISSUE TITLE
Error on root page of website

### ISSUE THREAD

**Issue by saschaende** [Yoast/Yoast-SEO-for-TYPO3#210]
Invalid value "HIDDEN" for enumeration "TYPO3\CMS\Core\DataHandling\TableColumnType" | TYPO3\CMS\Core\Type\Exception\InvalidEnumerationValueException

I get this error in the backend and on the page itself. This does not happen with version 3.0.2

**Comment by haassie** [comment]
Thanks for your report. There will be a patch by tomorrow

**Comment by saschaende** [comment]
Ah okay thanks. Actually switching back to 3.0.2 fixed it :)

**Comment by haassie** [comment]
That's correct, but you might have some issues with creating pages from the context menu with 3.0.2. Working on a patch right now. Not sure if I release tonight. Maybe better to check it tomorrow morning.

**Comment by saschaende** [comment]
Perhaps i did not get any errors before because i always use drag and drop :D

**Comment by saschaende** [comment]
Thanks at all for this nice extension!

**Comment by haassie** [comment]
Just released v3.0.4 which will hopefully fix your problem
