### ISSUE TITLE
Redirect searchfield empty after page switch and after editing your record

### ISSUE THREAD

**Issue by KoenWouters** [Yoast/Yoast-SEO-for-TYPO3#212]
### Please give us a description of what happened.
The searchfield of the redirects module is empty when i use the pagination to switch from page or when i click close after editing a redirect.

### Please describe what you expected to happen and why.
When i use the pagination or the close button after editing a redirect i expect the searchfield will be remembered.

### How can we reproduce this behavior?
1. In the redirect module fill in the searchfield en search
2. Now you have to switch from page using the pagination
3. The searchfield is now empty

OR

1. In the redirect module fill in the searchfield en search
2. Now you edit a record
3. Click close in the editing record screen
4. Searchfield is empty

### Screenshots
![screenshot 2018-09-26 09 20 10](https://user-images.githubusercontent.com/7394260/46063608-a0501900-c16d-11e8-8110-ae6406fed99a.png)
![screenshot 2018-09-26 09 20 16](https://user-images.githubusercontent.com/7394260/46063612-a2b27300-c16d-11e8-9521-10efd35cb50a.png)

### Technical info
* TYPO3 version: 8.7.18
* Yoast SEO version: 2.1.0 -- Premium 1.1

**Comment by RinyVT** [comment]
I'm going to close this issue, since the redirects are being handled by TYPO3 core nowadays (`EXT:redirects`)
