### ISSUE TITLE
No title - Yoast does'nt work

### ISSUE THREAD

**Issue by fxp66** [Yoast/Yoast-SEO-for-TYPO3#216]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
In typo3 backend everything seems to work fine, but there is no title tag 

### How can we reproduce this behavior?
1.
2.
3.

### Logs
If applicable, add logs to help explain your problem.

### Additional context
<pre>
<meta name="robots" content="," />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="RACO " />
<meta name="twitter:card" content="summary" />
</pre>

### Technical info
* TYPO3 version: 8.7.9
* Yoast SEO version: 2.1..0
* Relevant extensions in case of a bug:

**Comment by haassie** [comment]
Due to no response and because I can't reproduce, I will close this issue. If you think this is still an issue, please reopen this ticket.
