### ISSUE TITLE
YoastSEO Sitemap no subpage under a shortcut

### ISSUE THREAD

**Issue by lmwa** [Yoast/Yoast-SEO-for-TYPO3#217]

**Comment by olivermeckel** [comment]
is there any solution? We have the same problem.

all normal pages (doktype 1) which are below a shortcut (doktype 4) are not listed in the sitemap.xml

when we add the doktype 4 (shortcuts) by typoscript
`additionalWhere = AND doktype IN (1, 4)`
all normal pages below a shortcut are shown, but the shortcuts themeselve generate a temporary redirect 307 issue. Which is not so good for seo.

We are using
typo3 8.7.19
yoast_seo 3.0.4

**Comment by lmwa** [comment]
hey olivermeckel,

we also have the same problem with the 307 issue, we try to redirect in htaccess with 301 rules.
Old Article about this: https://www.krick-interactive.com/sem-blog/das-typo3-seo-302-307-redirect-desaster/

Greetings

**Comment by olivermeckel** [comment]
Hi lmwa,

thank you for the info. Our situation is a different.
We use shortcuts only to organize pages (clustering, leveling etc.)
All pagepaths are excluded from speaking urls and do not show up in frontend.

since use of yoast they were indexed by google and cause problems.

**Comment by lmwa** [comment]
hi olivermeckel,
thank you for sharing your information.
