### ISSUE TITLE
Add check if RouteEnhancers are configured

### ISSUE THREAD

**Issue by haassie** [Yoast/Yoast-SEO-for-TYPO3#220]
## Is your feature request related to a problem? Please describe.
In CMS9 if you have 1 RouteEnhancer configured you need to add RouteEnhancers for all page types. Because the snippet-preview is using a page type, you need to add a RouteEnhancer for that.

## Describe the solution you'd like
Check in the config if there are route enhancers configured. If so, check if the enhancer for the snippet preview is installed. If not, make sure a warning is given.

## why you think the feature request is something we should consider for the Yoast SEO plugins?
Because it will prevent support-issues.

**Comment by RinyVT** [comment]
Also check if JSON is valid, because if there's a type route but not for yoast, the homepage is shown which is a valid result but not a valid json.
