### ISSUE TITLE
PHP warnings with get_meta_tags and self signed SSL certificate

### ISSUE THREAD

**Issue by peterkraume** [Yoast/Yoast-SEO-for-TYPO3#222]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
In my local dev environment (DDEV) I have only a self signed SSL certificate.
Now every page I open in the page module produces three entries to the TYPO3 log:
```
Core: Error handler (FE): PHP Warning: get_meta_tags(https://xxxxx.ddev.local/): failed to open stream: operation failed in /var/www/html/private/typo3conf/ext/yoast_seo/Classes/UserFunctions/SnippetPreview.php line 16	
Core: Error handler (FE): PHP Warning: get_meta_tags(): Failed to enable crypto in /var/www/html/private/typo3conf/ext/yoast_seo/Classes/UserFunctions/SnippetPreview.php line 16	
Core: Error handler (FE): PHP Warning: get_meta_tags(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/private/typo3conf/ext/yoast_seo/Classes/UserFunctions/SnippetPreview.php line 16
```

### How can we reproduce this behavior?
1. use website with self signed SSL certificate
2. open any page in the page module
3. take a look at the log in the TYPO3 backend

### Technical info
* TYPO3 version: 9.5
* Yoast SEO version: 4.0

**Comment by nito-web** [comment]
I get the same error then you in your first line but without any cert / https and for me it results in a broken preview in the page module.

**Comment by haassie** [comment]
@nito-web and @peterkraume can you test if pull request #225 will fix your issue?
