### ISSUE TITLE
Snippet preview isn't working

### ISSUE THREAD

**Issue by olivermeckel** [Yoast/Yoast-SEO-for-TYPO3#223]
* [ x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

the snippet preview shows only default content for title, slug and description:

> This is an example title - edit by clicking here  
> example.com/example-post/
> Please provide a meta description by editing the snippet below.

Even with filled fields (Title for search engines and Description ) in the page properties tab "seo" there appears no correct preview.

The meta-Tags in the frontend are rendered correctly.

### Please describe what you expected to happen and why.

When no field are filled the snippet should show the page title.

### How can we reproduce this behavior?
Installing the extension. nothing else to do

### Screenshots
<img width="932" alt="bildschirmfoto 2018-10-26 um 13 31 52" src="https://user-images.githubusercontent.com/9928953/47564765-6322a680-d926-11e8-888a-61ebcf1f187f.png">

### Logs
nope

### Technical info
* TYPO3 version: typo3 9.5.0
* Yoast SEO version: 4.0.0
* Relevant extensions in case of a bug: bootstrap_package 10.0.2 (maybe?)

**Comment by haassie** [comment]
Hi Oliver,

Just checking: do you have any route enhancers in your setup? Because in that case, you need to add one for the Yoast snippet preview as well. 

For example:
```
routeEnhancers:
    PageTypeSuffix:
        type: PageType
        default: ''
        map:
            'sitemap.xml': 1533906435
            'yoast-snippetpreview.json': 1480321830
```
We have an open pull request to add a warning when this happens. Had this in my testrun of my presentation for T3CON18 as well.

**Comment by olivermeckel** [comment]
Yes, that's it

Thankx

**Comment by haassie** [comment]
We will add it to the documentation and have a warning in the snippet preview if this occurs.
