### ISSUE TITLE
sitemap.xml - not generated in typo3 9.5 LTS

### ISSUE THREAD

**Issue by vollyimnetz** [Yoast/Yoast-SEO-for-TYPO3#226]
Can anyone confirm that the sitemap.xml gets generated in 9.5? I didnt get one.
I am kind of new to typo3 - as far as i know real_url is not needed in 9.5 cause its build in. Did yoast work without real_url?

Also, is there any place to configure the generall/base settings for all pages (i.e. default facebook/og image)?

### Technical info
* TYPO3 version: 9.5 LTS
* Yoast SEO version: 4.0.0
* Relevant extensions in case of a bug:
  * blogging
  * bootstrap_grids
  * cewrap
  * gridelements
  * t3cms
  * t3content_bootstrap4
  * t3themes_bootstrap4
  * typo3_console

**Comment by haassie** [comment]
Hi,

Yes I can confirm that v9 is generating a sitemap. But the generation of the XML sitemap is done with core features in v9. The new version of EXT:yoast_seo is relying on those core features. You can find documentation on for example https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/XmlSitemap/Index.html.

All those features are now in core. If you have questions, you can ask in the Slack channel #cig-seo or if you find a bug, you can file an issue at https://forge.typo3.org.

I will close this issue.
