### ISSUE TITLE
Sitemap should not render records on disabled detail pages

### ISSUE THREAD

**Issue by ayacoo** [Yoast/Yoast-SEO-for-TYPO3#228]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
Because of my misconfiguration (set a disabled page) the sitemap.xml render x empty entries. The loc Tag is empty because
$cObject->typoLink_URL($typoLinkConf); don't find the target detail page.

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/release/3.0/Classes/UserFunc/SitemapXml.php#L148

### Please describe what you expected to happen and why.
Sitemap shouldn't render hidden detail pages (here records) and add a log entry. No exception of course ;-)

### How can we reproduce this behavior?
1. Build a standard config for "other" plugins
2. Set the detailPid to a hidden and disabled page

### Technical info
* TYPO3 version: 8.7.20
* Yoast SEO version: 3.0.4
* Relevant extensions in case of a bug: news

**Comment by ayacoo** [comment]
@RinyVT approved

**Comment by haassie** [comment]
Fixed by #236
