### ISSUE TITLE
Snippet preview on large pages causes browser tab to freeze

### ISSUE THREAD

**Issue by typecat** [Yoast/Yoast-SEO-for-TYPO3#232]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
If I click on a page with a large amount of content elements in page module, the snippet preview takes up to 1 min to load and often even causes the browser tab to freeze. The browser then shows a message, that the tab is not responding.
There are no JavaScript errors in the browser console.

### Please describe what you expected to happen and why.
I expected the browser not to freeze.
I expected to be able to edit content on the page a few seconds after clicking on it (like it does if snipped preview is disabled).

### How can we reproduce this behaviour?
1. Create a page with about 30 content elements.
2. Click on the page in the page module.
3. Wait for the snippet preview to load.

### Additional context
We are using EXT: flux for page templates and content elements (also structured content elements like containers).
The performance on pages with less content is fine. The performance with snipped preview disabled is also fine, even on large pages.
It doesn't seem to depend on internet connection as the issue was originally reported by our customer and we are able to easily reproduce it.
The page uses SSL also for back end.

### Technical info
* TYPO3 version: 7.6.30
* Yoast SEO version: 3.0.4
* Relevant extensions in case of a bug:
  * EXT: flux 7.4.0
* Browsers tested:
  * Firefox 63.0.3
  * Chrome 70.0.3538.110

**Comment by typecat** [comment]
I've found no such issue for the TYPO3 extension, but maybe this corresponds with the WordPress plugin issue: https://github.com/Yoast/wordpress-seo/issues/11356

**Comment by haassie** [comment]
We are working on a new implementation of the YoastSEO library. This update will also decrease the changes of browser windows to crash. The current way of the library is to do all analysis in the main thread of your browser causing the browser to hang when a lot of content have to be analysed. This new implementation will be available for CMS8 and 9. I'm not sure if we can easily backport this to CMS7 as well, because this will be a pretty big update of the extension.

**Comment by typecat** [comment]
Thank you for the update. We're currently upgrading the project to TYPO3 8.7. We look forward to the new version and will test it then ;)

**Comment by haassie** [comment]
Not sure when that version is production ready, but stay tuned. For now, I will close this particular issue because we can't really solve this with the current JS in CMS7.
