### ISSUE TITLE
Pages sitemap root ignore additionalWhere setting

### ISSUE THREAD

**Issue by ayacoo** [Yoast/Yoast-SEO-for-TYPO3#233]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Our base construct use "main separator" (doktype 254) This separator is also our "rootPid" for the pages sitemap- We exclude the doktype via additionalWhere and see that the main separator page is also listed in the sitemap.

### Please describe what you expected to happen and why.

I expect the root page to be handled according to my settings. (PR will follow)

### How can we reproduce this behavior?
Fast example:
1. Set rootPid = 1
2. Set `additionalWhere = AND uid >1`

Page with ID 1 is shown because of `$docs[] = $tsfe->sys_page->getPage($rootPid);`

### Technical info
* TYPO3 version: 8.7.20
* Yoast SEO version: 3.0.4

**Comment by ayacoo** [comment]
Possible solution

`$rootPage = reset($this->getTSFE()->sys_page->getMenuForPages([$rootPid], '*', 'sorting', $where));
 if ($rootPage) {
$docs[] = $rootPage;
}`

**Comment by RinyVT** [comment]
@ayacoo Could you check if this PR fixes your issue?
https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/236
The sitemap is now being generated the same way as in CMS9.

**Comment by ayacoo** [comment]
@RinyVT approved

**Comment by haassie** [comment]
Fixed by #236
