### ISSUE TITLE
Snippet Preview Error and Example Preview in Site Edit

### ISSUE THREAD

**Issue by helsner** [Yoast/Yoast-SEO-for-TYPO3#242]
Currently i get an error message inside the snippet preview when accessing a normal page
![bildschirmfoto 2019-01-18 um 09 47 04](https://user-images.githubusercontent.com/16156392/51375533-6e8d0480-1b06-11e9-9182-3028d190fd87.png)

Clicking the link leads to:
> {"error":"Could not read the url \/: "}

Inside the page properties i get the example snippet instead of the page 
![bildschirmfoto 2019-01-18 um 09 50 59](https://user-images.githubusercontent.com/16156392/51375594-9714fe80-1b06-11e9-95e9-bc6f2d3ce4ff.png)

System: Core 9.5.3 - Yoast 4.1

**Comment by haassie** [comment]
@helsner do you have configured a site with a domainname in the site management module?

**Comment by helsner** [comment]
I had one defined just with "/"
I tried a proper URL and it's now working.. 😅

**Comment by haassie** [comment]
In the next version, we will try to show a warning when you don't have a site configured with a domainname. This is kind of a requirement to work correctly. For now, I will close this issue.
