### ISSUE TITLE
Add basic auth support

### ISSUE THREAD

**Issue by imminger** [Yoast/Yoast-SEO-for-TYPO3#243]
Yoast 4 lost basic auth support. When basic auth is on, the snippet preview on a site no longer works. Also the Yoast fields in the page properties are blank. When basic auth is off, everything works fine.

The cause of the issue has been described by Richard Heaser on Slack: "Because of issues with cross-domain (for multi-domain-setups) we decided to make sure the URL is analyzed by a PHP script in the last version. Before it was an AJAX-call and this was using your current user/pass combination for basic auth. In the new version, the PHP script don’t know about your username and password."

## Describe the solution you'd like
It would be perfect, if one could use the Yoast functionality even when basic auth is on (like with Yoast 3 and TYPO3 8).

## why you think the feature request is something we should consider for the Yoast SEO plugins?
So editors can optimizes pages before the site is released.

## Additional context
Tested with TYPO3 9.5.3 and Yoast 4.1.0

**Comment by imminger** [comment]
There's an easy workaround for this issue: if you add **require ip [ip address of server]** to the htaccess file, the snippet preview will work as expected.

**Comment by akiessling** [comment]
Would still be nice to have such an option, e.g. if your server can have multiple/ varying ips

**Comment by RinyVT** [comment]
I have not tested this yet, but we use the function `GeneralUtility::getUrl` which calls the `RequestFactory`.
Inside the `RequestFactory` the configuration within `$GLOBALS['TYPO3_CONF_VARS']['HTTP'];` is used.
If I'm not mistaken, you should be able to provide the basic auth configuration this way:
```
$GLOBALS['TYPO3_CONF_VARS']['HTTP']['auth'] = ['username', 'password'];
```

**Comment by akiessling** [comment]
There is no such option
https://github.com/TYPO3/TYPO3.CMS/blob/c531ffa9d1b1d9e0eb756f229d444840d0b2fad3/typo3/sysext/core/Configuration/DefaultConfiguration.php#L1341

And even if there was, you would not want to send your credentials along with every outbound http request. IMHO, such a configuration should happen in the extension configuration or even better on pagets level.

**Comment by RinyVT** [comment]
"There is no such option".
Yes there is, but it is not a TYPO3 configuration but a Guzzle configuration:
https://github.com/TYPO3/TYPO3.CMS/blob/v9.5.7/typo3/sysext/core/Classes/Http/RequestFactory.php#L48-L51

But I agree this option would be set system-wide and you do not want to send this with other outgoing requests. We'll have a look at providing some configuration for this, thank you for the suggestion extension-manager with an override on pagets level!

**Comment by akiessling** [comment]
Alright, thanks for the hint. Unfortunately, i can't use that workaround.

**Comment by ayacoo** [comment]
Is there already a decision here which is planned? Can I support somehow here?

**Comment by RinyVT** [comment]
Closing this issue, last December the possibility for basic authentication was added:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/397

Feel free to open a new issue if this does not work for you.
