### ISSUE TITLE
After deleting default image using "remove current image" checkbox, reference is still found in the Filelist

### ISSUE THREAD

**Issue by dkd-end** [Yoast/Yoast-SEO-for-TYPO3#247]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Using the Module "Settings" I set global images for Twitter and Facebook and saved.
Afterwards using the Checkbox "Remove the current Image" to delete images and saved.
Image is correctly deleted in Frontend.
However, the image is still listed in the Filelist in Backend, with a reference to the main page (ID=1).
It cannot be deleted in the Filelist.

### Please describe what you expected to happen and why.
When pressing a button to remove the current image, i expect that to happen, because the button said it would do that.

### How can we reproduce this behavior?
1. YOAST SEO Module Settings
2. Upload new File (for Twitter or Facebook) and save
3. Click Checkbox to "remove the current image" and save
4. Open Module "Filelist" and try to delete the File you just uploaded

### Technical info
* TYPO3 version: 8.7.24
* Yoast SEO version: 3.0.5
* (Not sure if) Relevant extensions in case of a bug: Yoast SEO for TYPO3 - EXT:news 1.1.0

**Comment by RinyVT** [comment]
Closing this issue since we do not provide the default images setup (and the Settings module) anymore.
If there are any other problems, feel free to open a new issue.
