### ISSUE TITLE
Page-editor doesn't show analysis fields when using quote(s) in Focuskeywords

### ISSUE THREAD

**Issue by mhuijser** [Yoast/Yoast-SEO-for-TYPO3#250]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

When using a quote in te field "Focuskeyword" the analysis-fields in the page-editor keeps "Loading", and a few javascript errors appear in the console

### Please describe what you expected to happen and why.

I expected the editor to keep working ;-) 

### How can we reproduce this behavior?
1. Fill the "Focuskeywords" field with a string containing one or more quotes
2. save and close the page-editor
3. reopen the page-editor, and see that it doesn't work

### Screenshots

![schermafbeelding 2019-03-07 om 12 26 32](https://user-images.githubusercontent.com/1103915/53961218-5b4eec00-40e8-11e9-9bba-0f89d6f72e9b.png)

![schermafbeelding 2019-03-07 om 13 36 20](https://user-images.githubusercontent.com/1103915/53961231-61dd6380-40e8-11e9-8152-9987088eb790.png)

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 8.7.24
* Yoast SEO version: 3.0.4
* Relevant extensions in case of a bug:

**Comment by haassie** [comment]
This is fixed with the today released version.
