### ISSUE TITLE
Browser Crash 

### ISSUE THREAD

**Issue by woodyc79** [Yoast/Yoast-SEO-for-TYPO3#252]
Hello!
Today I purchased Yoast Premium 1.0 for 2 TYPO3 Pages... unfortunately with Yoast 3.0.5 (TYPO3 7.6.x) I get a "Paused befire potential out of memory crash" when displaying the page properties / Yoast SEO Tab.
![yoast_seo_crash](https://user-images.githubusercontent.com/1710712/55258156-5520db00-5262-11e9-9c47-ba939cb29a6b.png)
Any suggestions?
Thank you!

**Comment by haassie** [comment]
Hi. Do you have a page with a lot of content on it? We are currently in the process of reworking the JS which will fix this kind of issues. We expect to release this version early next week. We are currently testing the last parts.

BTW, if you have premium you can use our support team to get priority support!

**Comment by haassie** [comment]
With the today released version, this should be gone. If you still have the issue, please open a new ticket or contact us via support.

**Comment by woodyc79** [comment]
Hello! Thank you!
But for TYPO3 7.6 i do not find new version via composer?

**Comment by haassie** [comment]
Ah sorry. The new version is indeed only for CMS8 and 9. If wanted we can made a (paid) backport, but we won’t release any free new versions for CMS7.
