### ISSUE TITLE
Language x does not exist on site root issue after Upgrade to 5.0.0

### ISSUE THREAD

**Issue by bibusdax** [Yoast/Yoast-SEO-for-TYPO3#255]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

I installed the upgrade to Yoast 5.0.0 and immediately thereafter all our webpages started to fail with the following error message:

(1/1) #1522960188 InvalidArgumentException

Language 27 does not exist on site root.

### Please describe what you expected to happen and why.

I expected our website to work as ever before

### How can we reproduce this behavior?
1. Upgrade to Yoast 5.0.0
2. Activate it
3.

### Logs
If applicable, add logs to help explain your problem.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1522960188: Language 6 does not exist on site root. | InvalidArgumentException thrown in file /var/www/clients/client1/web1/web/typo3_src-9.5.5-patched/typo3/sysext/core/Classes/Site/Entity/Site.php in line 236. Requested URL: https://www.bibus.ch/produkte-und-loesungen/daempfungstechnik/bansbach-gasfedern-und-oelbremsen/bansbach-sondergasfedern 

### Additional context

Obviously Yoast is messing up big time with the language detection stuff.
I really did not expect that.

### Technical info
* TYPO3 version: 9.5.5
* Yoast SEO version: 5.0.0
* Relevant extensions in case of a bug:

**Comment by haassie** [comment]
Can you give me more background information? The extension is of course tested with a multi language setup. 

Have you configured your sites in the site management?

**Comment by haassie** [comment]
Btw, do you get these errors in Frontend or backend?

**Comment by bibusdax** [comment]
Dear Richard,

I can give you more information and if you want, I could give you access to a fresh “test” clone so that you can see for yourself what happens when the update is installed.
We have yoast_seo 4.1.0 installed and with that we upgraded our System from 8LTS to 9LTS 9.5.5-patched as we had to patch the core for various bugs and compatibility issues.
On Monday I saw that yoast_seo and yoast_news have updates available, so I installed them and immediately thereafter I saw error logs.
Then I realized that no website was working anymore in that installation.
As a consequence I deactivated yoast, removed the yoast folders and replaced them with the backup of the previous ones, activated that one and everything was working again.

Our setup:
We have now 33 languages installed.
We have more than 50 root sites in our TYPO3
We have them all configured in the Site Management
Also they have their own root flag set and we have additional configurations in the Templates

Btw. We also have the problem that yoast_premium 1.1 does not work anymore with 9LTS.

Thank you very much for your quick feedback and best regards,

Patrick Daxboeck
IT-Consultant Web

BIBUS HOLDING AG
Allmendstrasse 26
8320 Fehraltorf
Switzerland
Direct   +41 44 877 50 34
Mobile  +41 76 331 00 31
E-Mail   dax@bibus.ch
Internet www.bibus-holding.ch



Von: Richard Haeser [mailto:notifications@github.com]
Gesendet: Dienstag, 16. April 2019 20:00
An: Yoast/Yoast-SEO-for-TYPO3
Cc: Daxboeck Patrick; Author
Betreff: Re: [Yoast/Yoast-SEO-for-TYPO3] Language x does not exist on site root issue after Upgrade to 5.0.0 (#255)


Can you give me more background information? The extension is of course tested with a multi language setup.

Have you configured your sites in the site management?

**Comment by haassie** [comment]
Hi Patrick,

There is not that much in frontend what the Yoast extension does in CMS9 so it is really weird that you get messages from that. If I understand correctly you are not working composer-based? You didn't install the new Yoast SEO Premium for TYPO3? It is really important to do that to still have the premium features. 

Because you are a premium client, we can offer you some support in this. So if you could create a fresh copy for us and send us the credentials by a support ticket via support@yoast.com, than we will have a look at it. 

Meanwhile I will leave this issue open until we can decide if it is a bug for the plugin.

Best regards,

Richard

**Comment by bibusdax** [comment]
Dear Richard,

Thank you very much for your quick reply.

In our upgrade testing yoast_premium_1.1 did cause issues, so we had to deactivate it.
Also the plugin itself states that it is not compatible with 9LTS.
I already filed a support ticket at yoast! Themselves and they wrote that it was being forwarded.

I am used to install extensions and their updates via the backend. However that should not make any difference to using composer.

Btw. I am looking forward to meet you again in “the hague”.

Best regards,

Patrick

Von: Richard Haeser [mailto:notifications@github.com]
Gesendet: Mittwoch, 17. April 2019 07:21
An: Yoast/Yoast-SEO-for-TYPO3
Cc: Daxboeck Patrick; Author
Betreff: Re: [Yoast/Yoast-SEO-for-TYPO3] Language x does not exist on site root issue after Upgrade to 5.0.0 (#255)


Hi Patrick,

There is not that much in frontend what the Yoast extension does in CMS9 so it is really weird that you get messages from that. If I understand correctly you are not working composer-based? You didn't install the new Yoast SEO Premium for TYPO3? It is really important to do that to still have the premium features.

Because you are a premium client, we can offer you some support in this. So if you could create a fresh copy for us and send us the credentials by a support ticket via support@yoast.com<mailto:support@yoast.com>, than we will have a look at it.

Meanwhile I will leave this issue open until we can decide if it is a bug for the plugin.

Best regards,

Richard

**Comment by haassie** [comment]
Patrick,

Will check with Yoast. That mail is containing credentials for a non-production site? 

Please know that you should update your premium extension to version 3.0.0 now. 

Will switch to support-ticket for this.

**Comment by haassie** [comment]
As discussed at the helpdesk, this was mainly because of some bugs in core. I will close this issue and when something is broken in Yoast SEO, we can open a new issue.
