### ISSUE TITLE
Unknown column 'sys_language_uid' in 'where clause'

### ISSUE THREAD

**Issue by georgringer** [Yoast/Yoast-SEO-for-TYPO3#258]
Just reporting a bug a friend got using latest yoast_seo in a 8.7 project. 

```
An exception occurred while executing 
'SELECT * FROM `pages` WHERE (`tx_yoastseo_cornerstone` = 1) AND (`sys_language_uid` = 0) AND ((`pages`.`deleted` = 0) AND (`pages`.`hidden` = 0) AND (`pages`.`starttime` <= 1555692900) AND ((`pages`.`endtime` = 0) OR (`pages`.`endtime` > 1555692900)))': 
Unknown column 'sys_language_uid' in 'where clause'
```

I am *guessing* this is because in 8.7 there is still `pages_language_overlay` and no column `sys_language_uid` in table `pages`.

**Comment by fvonellerts** [comment]
I also had this problem in TYPO3 9, analyzing the database fixed the conflict:
Maintenance > Analyze Database Structure
