### ISSUE TITLE
Yoast v. 5.0 breaks TYPO3 v. 8.7.11

### ISSUE THREAD

**Issue by Melanzana27** [Yoast/Yoast-SEO-for-TYPO3#259]
When I upload the Yoast SEO 5.0 extension via the Extension manager my site breaks, FE and BE. This happens on 2 different sites using v. 8.7.11

I get this error:

```
Uncaught TYPO3 Error

Return value of YoastSeoForTypo3\YoastSeo\StructuredData\StructuredDataProviderManager::initCaches() must be an instance of YoastSeoForTypo3\YoastSeo\StructuredData\void, none returned 

TypeError thrown in file
/var/www/t3-8-dev.wng.ch/web/typo3conf/ext/yoast_seo/Classes/StructuredData/StructuredDataProviderManager.php in line 165.
```

I tried both .zip and T3X file and get the same error.

Yoast v.3.0.5 works fine

### Recreate the error
* Download Yoast 5.0 .zip file or T3X file
* Upload it via the extension manager on a 8.7.11 TYPO3
* Site crashes

### Technical info
* TYPO3 version: 8.7.11
* Yoast SEO version: 5.0

**Comment by haassie** [comment]
Hi,

Which PHP-version do you use?

**Comment by Melanzana27** [comment]
Hi,

PHP Version 7.0.4

**Comment by haassie** [comment]
Clear. Will create a fix. We used a PHP-function 7.1+.

**Comment by Melanzana27** [comment]
Thank you, works fine !
