### ISSUE TITLE
Snippet preview triggers visibility of inactive sites in frontend menus

### ISSUE THREAD

**Issue by vixe76** [Yoast/Yoast-SEO-for-TYPO3#272]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
After editing a page with Snippet Preview all inactive pages are generally shown in the frontend menus (also for none logged in users). 

I suspect the problem is that the Snippet Preview generates a new page cache after editing this page for the logged in BE user.

### Please describe what you expected to happen and why.
Showing inactive pages links in frontend (without BE login) should be never allowed.

### How can we reproduce this behavior?
1. Make a page inactive inside a frontend menu
2. Edit another page which contains the affected menu
3. Look at the frontend of the edited page and the inactivated page is in the menu visible

### Technical info
* TYPO3 version: 9.5.7
* Yoast SEO version: 5.0.1

**Comment by vixe76** [comment]
Hello and sorry for pushing this, but I think this is an urgent bug and for me the extension is not usable in production environments! Can't believe that I'm the only one who is affected!? 

Please let me know if additional informations are needed.  

Best Regards
Falk

**Comment by RinyVT** [comment]
Hi @vixe76 
This problem was due to the Middleware setting the Visibility scope so it's possible to preview hidden pages in the backend.
Could you test if this PR fixes your problem?
https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/275

**Comment by vixe76** [comment]
Hi @RinyVT 
I've tested successfully your PR ... fixes my problem!

Thanks and Greetings
