### ISSUE TITLE
In page analytics slow & often don't show?

### ISSUE THREAD

**Issue by pranath-liquidlight** [Yoast/Yoast-SEO-for-TYPO3#273]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

I have installed the plugin on typo3 v 8.7.25. For the in-page analytics for most pages it does not work - so I see the 'loading' 3 dot icons - but it never completes (see screenshot). 

Very occasionally it does work (see other screenshot).

Does anyone know why? seems like a bug?

Yoast seo version 5.0.1

**Comment by haassie** [comment]
The new version is rendering the complete frontend to check the complete page. This is done by a server request. Sometimes we see that the server connection to the own domain is sometimes pretty slow. We are working on an update to show the exact error when this occurs (like a timeout)

**Comment by RinyVT** [comment]
I will close this issue for now due to the age of this issue and the version this was applicable to.
We have made several improvements to the error handling of the snippet preview, feel free to open a new issue if there's still something wrong.
