### ISSUE TITLE
Sitemap record url not correct

### ISSUE THREAD

**Issue by jagodzinski** [Yoast/Yoast-SEO-for-TYPO3#277]
Hello,

The Sitemap for Records uses the uid to render the url. Therefor you have "wrong" urls because extbase always use the original url of the language parent.

So if you have a Record wich is Named ABC in all languages and you use useUniqueCache in realurl the urls on a list page are
www.example.com/de/record/abc
www.example.com/en/record/abc
and in the sitemap it's
www.example.com/de/record/abc
www.example.com/en/record/abc-1

It's a problem because the url is not like the canonical.

This problem can be solved if you use the parent if it exist in following code:
yoast_seo/Classes/UserFunc/SitemapXml.php
```
protected function getRecords($sitemapSettings)
    {
...
$typoLinkConf['additionalParams'] = '&' . $sitemapSettings['additionalParams'] . '=' . $record['uid'];
..
     }
```

### Technical info
* TYPO3 version: TYPO3 8
* Yoast SEO version: 3.0.5
* Relevant extensions in case of a bug: realurl
[SitemapXml.php.patch.zip](https://github.com/Yoast/Yoast-SEO-for-TYPO3/files/3323793/SitemapXml.php.patch.zip)

**Comment by RinyVT** [comment]
Closing this issue due to the age and the drop of CMS8 support since the last version.
The sitemap is handled by the TYPO3 core (`EXT:seo`) nowadays.
