### ISSUE TITLE
Always empty list for pages without meta description in TYPO3 v8.7

### ISSUE THREAD

**Issue by froschdesign** [Yoast/Yoast-SEO-for-TYPO3#280]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

In version 8.7 of TYPO3 CMS the data provider for pages without descriptions only uses the database table `pages_language_overlay`. Therefore the list is always empty if the language setting is "default".

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/12712d9641c0faf84d7501819da39a4960c71d90/Classes/DataProviders/PagesWithoutDescriptionOverviewDataProvider.php#L36-L40

### Please describe what you expected to happen and why.

List all pages without meta description also for language "default". This means for version 8.7 that the database table `pages` must be used as well.

* related issue report: #258 – this bug report is correct
* related pull request: #260 – this pull request had resolved the reported problem in #258 but introduced the current issue

### How can we reproduce this behavior?

1. Open the overview of Yoast plugin
2. Choose language "default"
3. Choose pages without meta description

### Technical info

* TYPO3 version: 8.7.27
* Yoast SEO version: 5.0.1

**Comment by RinyVT** [comment]
Hi @froschdesign, could you check if this fixes your issue?
https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/281

**Comment by froschdesign** [comment]
@RinyVT 
Works like a charm! (Tested in a local installation.) 👍 

Thank you very much.

**Comment by froschdesign** [comment]
Btw. works for the language setting "Standard" and also for other languages.
