### ISSUE TITLE
getAllowedDoktypes in frontend context

### ISSUE THREAD

**Issue by RinyVT** [Yoast/Yoast-SEO-for-TYPO3#283]
* [*] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [*] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
When clearing the cache and accessing the frontend, the cache will get build with frontend-context.
The function getAllowedDoktypes does not return the additional (user) defined doktypes in frontend-context, which causes the TCA to not get build on these additional doktypes.

### Please describe what you expected to happen and why.
getAllowedDoktypes works in frontend context.

### How can we reproduce this behavior?
1. Define an additional doktype within module.tx_yoastseo.settings.allowedDoktypes
2. Clear all caches
3. Access the frontend before the backend generates the new caches
4. See the generated TCA

**Comment by haassie** [comment]
Fixed with https://github.com/Yoast/Yoast-SEO-for-TYPO3/commit/63a1ea8d5101dced6c91195d559c760686d33260
