### ISSUE TITLE
Typo3 9.5.8 Preview in the Backend not working

### ISSUE THREAD

**Issue by Tiimiiiboy** [Yoast/Yoast-SEO-for-TYPO3#284]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
Hello everybody,
I have installed the Yoast Extension on my Typo3 installation. Unfortunately I do not see the preview in the backend.

In the developer console of Chrome I get the error message:

### Error Log
plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51 TypeError: Cannot read property 'replace' of undefined at e.default (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:34) at e.value (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:68) at e.value (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:68) at qr (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51) at Ar (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51) at Rr (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51) at Yo (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51) at Go (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51) at Cs (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51) at As (plugin.js?bust=897ad4fc953dfe2b250a6e2afc179f32e1bd5230:51)

### Technical info
TYPO3 version: 9.5.8
Yoast SEO version: 5.0.1
Bootstrap_Package: 11.0.0

**Comment by web2date** [comment]
Some issue here...
TYPO3 v 9.5.9 Yoast 5.0 + 5.0.1

**Comment by haassie** [comment]
This has something to do that the server cannot access the page to analyse. In the master-branch, you get a proper message now that can help you identify the problem. At least you don't get any console errors anymore.
