### ISSUE TITLE
Backend preview snippet shows raw/unparsed HTML

### ISSUE THREAD

**Issue by bjo3rnf** [Yoast/Yoast-SEO-for-TYPO3#290]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
The backend preview snippet shows raw/unparsed HTML of the page's body when the meta description is not filled in.

### Please describe what you expected to happen and why.
I'd expect to see the default text instead (`Please provide a meta description by editing the snippet below.[...]`)

### How can we reproduce this behavior?
Empty the description of a page and save it

### Screenshots
![Bildschirmfoto 2019-08-29 um 12 44 32](https://user-images.githubusercontent.com/1183009/63941468-032bed80-ca6c-11e9-9d66-b76a13192669.jpg)

### Technical info
* TYPO3 version: 9.5.9
* Yoast SEO version: 5.0.1
* Relevant extensions in case of a bug: filefill, news, vhs, custom site package (nothing fancy)

Thanks a lot in advance!

**Comment by Jashi** [comment]
We couldn't reproduce the raw HTML (our first content element on the page was an HTML element with a youtube iframe) but we also don't see the default text, we see the first content of the page. Maybe it's meant to be this way with the new Yoast version?

**Comment by bjo3rnf** [comment]
Ok, thanks for checking. It seems to be a problem on my side then. I will have another look.

**Comment by brotkrueml** [comment]
In the rendered HTML page the following code is embedded direct after the body tag:

`<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXXX" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`

Then the code is shown as in the screenshot above. Please note, that the noscript tag is not shown in the snippet.

**Comment by bjo3rnf** [comment]
@brotkrueml you are right, thanks. Let's see what we can do to fix that on either side.
