### ISSUE TITLE
Exclude option to true for all tca fields

### ISSUE THREAD

**Issue by ayacoo** [Yoast/Yoast-SEO-for-TYPO3#291]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
I use an editor account and see the tx_yoastseo_focuskeyword_synonyms field in the page settings

### Please describe what you expected to happen and why.
I would like to exclude all fields which comes from yoast Extension for some user groups.

### How can we reproduce this behavior?
1. Use an editor and restrict all fields in "pages" to false
2. Open the page settings of a page

https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Configuration/TCA/Overrides/pages.php#L90

### Technical info
* TYPO3 version: 9.5.9
* Yoast SEO version: 5.0.0 (premium)

**Comment by haassie** [comment]
You can already override this by overriding the TCA config in your own extension. As this is a breaking change for existing installations, we will not add this to the default setup.
