### ISSUE TITLE
Remove sitename from the page title

### ISSUE THREAD

**Issue by shabnamKhan** [Yoast/Yoast-SEO-for-TYPO3#293]
I want to remove the site name from the page title. I didn't found any option to remove sitename from the page title.

**Comment by haassie** [comment]
This is a support question. If you want support, you can check the #yoast-seo-for-typo3 channel on [Slack](https://typo3.org/article/how-to-use-slack-in-the-typo3-community/) or even better: order your [premium subscription](https://yoast.com/typo3-extensions-seo/) so we can help you with the installation and configuration.

We can't do any support within GitHub.
