### ISSUE TITLE
Breadcrumbs markup error

### ISSUE THREAD

**Issue by janslu** [Yoast/Yoast-SEO-for-TYPO3#297]
* [X ] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Search Console shows an error in markup on my site. The error is `Invalid top level element "array"` This is the ld+json part of the source code:
```
<script type="application/ld+json">[{"@context":"https://www.schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.babyboom.pl/","name":"Babyboom"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.babyboom.pl/ciaza","name":"Ci\u0105\u017ca"}},{"@type":"ListItem","position":3,"item":{"@id":"https://www.babyboom.pl/ciaza/kalendarz-ciazy","name":"Kalendarz ci\u0105\u017cy tydzie\u0144 po tygodniu"}},{"@type":"ListItem","position":4,"item":{"@id":"https://www.babyboom.pl/ciaza/kalendarz-ciazy/37-tydzien","name":"37. tydzie\u0144 ci\u0105\u017cy"}}]},["pageId_1888"]]</script>
```

### Please describe what you expected to happen and why.

The last part of the array `,["pageId_1888"]` is an error. Also - I didn't find a way to disable this markup completely. My breadcrumbs already have proper markup and Yoast's is redundant (and it's worse, because I have shortened the homepage title for example)... 

### How can we reproduce this behavior?
1. Installed and enabled Yoast

### Technical info
* TYPO3 version: 9.5.9
* Yoast SEO version: 5.1.0 installed using composer... 
* Relevant extensions in case of a bug: can't think of anything particular...

**Comment by RinyVT** [comment]
Hi @janslu ,

I am unable to reproduce this issue. Could you check if this issue is still present in the latest version?
If so, could you check the `Typoscript Object Browser` to see what's registered under `config.structuredData.providers`?
Also, how is your tree setup? Do you have one root page or possibly a root page within a root page?
Thanks in advance.

**Comment by RinyVT** [comment]
Closing this issue due to lack of feedback (and the age of the issue), feel free to open a new issue if this still occurs.
