### ISSUE TITLE
Yoast SEO tab dissappears after periode time in TYPO3 backend

### ISSUE THREAD

**Issue by Redkiwi-Agent** [Yoast/Yoast-SEO-for-TYPO3#305]
* [ ] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

For our client we installed the YOAST SEO extension. The TYPO3 version is 8.7 and seems to be working fine initially, but after certain period of time the YOAST seo tab completely dissappears from the pages. We could not find anything in the loggin indicating any reason for this. This seems to be happening periodically.  After flushing the cache, the tab is returned to the places.

Worth noting, the current site is not yet deployed and launched and is currently running in a closed  accept environment but this shouldn't be a factor. 

### Please describe what you expected to happen and why.

- support regarding this issue as to why this is happening
- a structural solution to make sure the yoast seo tab doesnt periodically dissappears

### How can we reproduce this behavior?
1. We'd have to give a support engineer acces to the environment so you can check this
2. Because it's fixed now and it periodically (random) dissapears its hard to reproduce this 
3.

### Screenshots
https://screencast.com/t/yWngpCFW4

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 8.7.
* Yoast SEO version:
* Relevant extensions in case of a bug:

**Comment by KaiBroenstrup** [comment]
Anything new here? Any solutions?

**Comment by RinyVT** [comment]
Is this issue still present in the latest version?
In the past we've done some unconventional adjusting of TCA but as far as I can see we're only using core methods for adding fields and pallettes:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Configuration/TCA/Overrides/pages.php

If it's still an issue, are there maybe other extensions in the installation which also adjust the TCA of pages in the same area? Maybe it's a positional issue.

**Comment by rmeeuwissen** [comment]
@KaiBroenstrup @Redkiwi-Agent  Any updates/feedback from your end?

**Comment by RinyVT** [comment]
I'm going to close this issue due to the age of the issue, feel free to open a new issue if this still occurs with the latest version.
