### ISSUE TITLE
htmlentities in <title>-Tag

### ISSUE THREAD

**Issue by mweber1973** [Yoast/Yoast-SEO-for-TYPO3#307]
* [ x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

If we put charakters like ">" in the field "Title for search engines" these charakters are rendered as "_and_gt;" (as HTMLEntity) in the HTML-Source. In the Backend YOAST shows "_and_gt;" instead of ">"

(please replace "__and__" with "&")

### Please describe what you expected to happen and why.

I dont think the use of htmlentites in the <title>-Tag is necessary.....and our editors are a little bit confused by this :)

### How can we reproduce this behavior?
Just install Yoast and set the "Title for search engines" to ">Hello<"

### Technical info
* TYPO3 version: V9
* Yoast SEO version: 5.1.1

**Comment by RinyVT** [comment]
@mweber1973 
Although this is quite an old issue, this was still present in the latest versions.
Could you check if #398 fixes your issue?
