### ISSUE TITLE
Wrong version in ext_emconf.php for tag v5.1.1

### ISSUE THREAD

**Issue by typecat** [Yoast/Yoast-SEO-for-TYPO3#311]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
If installing EXT:yoast_seo via composer requiring ^5.1, the installed version in composer.lock is 5.1.1 but the ext_emconf.php file shows the version 5.1.0.

See https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/v5.1.1/ext_emconf.php

### Please describe what you expected to happen and why.

I expect to see version 5.1.1 in ext_emconf.php file if composer.lock file says that version 5.1.1 was installed.

### How can we reproduce this behavior?
1. composer req yoast-seo-for-typo3/yoast_seo ^5.1
2. composer install
3. View the EXT:yoast_seo/ext_emconf.php

### Technical info
* TYPO3 version: 8.7.24
* Yoast SEO version: 5.1.1

**Comment by haassie** [comment]
As I don't want to change the code of an existing tag and as we already have v6, I will close this issue. When we are releasing a new v5 update, we will update the version number.
