### ISSUE TITLE
Make Canonical URL configurable in Backend

### ISSUE THREAD

**Issue by Barakur** [Yoast/Yoast-SEO-for-TYPO3#312]
## Is your feature request related to a problem? Please describe.

The Yoast SEO extension adds the column caonical_link to the pages table and checks it when creating a canonical link but no backend element exists to actually change it.

## Describe the solution you'd like

I would like a textfield in the backend to customize the canonical URL

## why you think the feature request is something we should consider for the Yoast SEO plugins?

Customizing of the canonical url is already supported by the Yoast SEO extension, so why doesn't the extension provide a textfield for it?
It seems the feature is 70% done and the backend textfield is just missing.

## Additional context

I required customizing of the canonical url for some pages and wrote a simple extension to just add the textfield to the backend. To not provide it by default seems like an oversight to me.

**Comment by RinyVT** [comment]
Hi @Barakur,

Which version of TYPO3 and Yoast SEO are you using? In TYPO3 8.7 the canonical field is at the bottom of the "Yoast SEO" tab:
![Schermafbeelding 2019-12-12 om 15 51 49](https://user-images.githubusercontent.com/4457119/70722359-6f6aee00-1cf7-11ea-95e5-ade5d3c78853.png)

For CMS9 this has become a core field, and is available at the bottom of the "SEO" tab.

**Comment by Barakur** [comment]
Hi @RinyVT,

I'm using Typo3 8.7.29 with Yoast 3.0.5 in classic mode.
The bottom of the Yoast SEO tab looks like this:

![image](https://user-images.githubusercontent.com/35734421/70787161-6a0cb280-1d8e-11ea-839a-89e0854afaa0.png)

As you can see there is no canonical field.

**Comment by RinyVT** [comment]
Hi @Barakur,

That is weird, my screenshot is also from a TYPO3 8.7.29 installation with Yoast SEO 3.0.5.
Since version 3.0.5 there have been some changes to the TCA of pages (current stable version 5.1.1). Could you try updating and see if that fixes the issue?

**Comment by Barakur** [comment]
Hi @RinyVT 

Even with Yoast 5.1.1 the field is still missing. Are you maybe checking in composer mode instead of classic? I noticed that sometimes an extension in TER and Packagist are different although they have the same version.

**Comment by RinyVT** [comment]
Hi @Barakur,

You are right, I found the problem in 5.1.1 where the canonical field was missing in TCA.
I have opened a pull request for this problem, would be great if you have a chance to test this:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/318

**Comment by Barakur** [comment]
Sorry I didn't respond and was unable to test it but I got swamped with work + had to move.
Your PR seems to be accepted, thanks for your help.
