### ISSUE TITLE
Sysfolder is shown as page in json+ld @type BreadCrumbList

### ISSUE THREAD

**Issue by AMartinNo1** [Yoast/Yoast-SEO-for-TYPO3#314]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
In my page tree I have a sysfolder with subpages. The sysfolder get's listed with just the domain as `@id` which is the same as the Page "home". So, it ends up with that:
![image](https://user-images.githubusercontent.com/5464339/69166923-57d38780-0af4-11ea-8bd0-3f518b2e4709.png)
Result from: https://search.google.com/structured-data/testing-tool

### Please describe what you expected to happen and why.
Instead of either using the domain as url I'd expected it either to be ignored in the BreadCrumbList or shown `/metanavi` which is the slug when viewing the page record in my backend.

### How can we reproduce this behavior?
1. Create a page tree with a sysfolder as well as subpages
2. Check BreadCrumbList json+ld output

### Technical info
* TYPO3 version: v9.5.11
* Yoast SEO version: v5.1.0
* Relevant extensions in case of a bug:

**Comment by medarob** [comment]
We have the same error. We use Menu separators and hide them in the frontend (show in menu: disabled) but they are in the breadcrumb json+ld list and therefore Google shows them in the breadcrumbs. :/

Maybe it's possible to check for certain pagetypes and exclude them from the json+ld output?

A workaround would be to disable the json+ld output but I don't know how that can be done.

Yoast SEO 5.1.1 and TYPO3 9.5.14

**Comment by boettner-it** [comment]
It´s possible to configure the used types in TS setup like so: 
config.structuredData.providers.breadcrumb.excludedDoktypes = 1,3,4,199,254

**Comment by galum** [comment]
We had the same problem that data folders ended up in the json+ld breadcrumb data. The _excludedDoktypes_ config fixed the problem. It would be a nice feature however, if json+ld breadcrumb rendering could be disabled completely by a configuration value like this. For example, if the json+ld breadcrumb is generated elsewhere dynamically by considering the page parameters. 
The only solution for that what I could find is to exclude all known doktypes for the particular page for yoast-seo, but then still a script tag with empty array is rendered:

`<script type="application/ld+json">[]</script>`

Maybe enable/disable config options could generally also be considered for the other outputs that yoast-seo generates. That would be nice.

Thank you for your efforts.

**Comment by RinyVT** [comment]
As stated above, it's possible to exclude doktypes through
```
config.structuredData.providers.breadcrumb.excludedDoktypes = ...
```
If you want to disable the rendering of the JSON completely you can use:
```
config.structuredData.providers >
```

In the latest versions the JSON will not be rendered then, due to this commit:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/commit/af8ec1e4740c2164d7f1e4ab4e689a1aed3cb8fd

I will close this issue for now. If you feel like there's still something missing, feel free to open a new issue.
