### ISSUE TITLE
Language Issue -> .com (EN) .de (de)

### ISSUE THREAD

**Issue by dangele** [Yoast/Yoast-SEO-for-TYPO3#315]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
https://www.heinzinger.de/anwendungen/ (German)
https://www.heinzinger.com/applications/ (english)

at both languages we have the german SEO - Info

### Please describe what you expected to happen and why.
At the backend we have the option to edit the german and the english SEO information.
www.heinzinger.com -> englisch SEO output

### How can we reproduce this behavior?
1.
2.
3.

### Screenshots
![german](https://user-images.githubusercontent.com/56590474/69737276-69d8aa00-1134-11ea-87d1-985b6ed95113.png)
![english](https://user-images.githubusercontent.com/56590474/69737277-6a714080-1134-11ea-8859-921069e6806b.png)

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 7.6.23
* Yoast SEO version: 3.0.5
* Relevant extensions in case of a bug:

**Comment by RinyVT** [comment]
I'm going to close this issue, since the bug-report is for older TYPO3 and extension versions which we do not support anymore.
Feel free to open a new issue if this is still not working correctly in the new version (8.0)
