### ISSUE TITLE
Preview snippet does not work if default language is disabled via language tab option

### ISSUE THREAD

**Issue by Jashi** [Yoast/Yoast-SEO-for-TYPO3#320]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

I've checked the other issues with the snippet preview but since none of them had anything specific about the language disabling or the empty response I figured it might be a different problem.

### Please give us a description of what happened.
We have a multilanguage site and the default language page is "disabled" with "hide default translation of page". Obviously the preview snippet does not work for the default language but even when opening the translated page the snippet preview isn't working.

### Please describe what you expected to happen and why.
I expect there to be a working preview snippet for the translated page as it is visible in the frontend.

### How can we reproduce this behavior?
1. Add a page and enable it
2. Translate the page and enable it
3. Set the option "hide default translation of page" in the language tab of the page properties
4. Edit the page properties of the translation and open the SEO tab
5. If you're lucky, you'll see the error message "The server was not able to access the page to analyse your content. When trying to fetch , a -1 status code was received. Please make sure your server can access the page". If you're not lucky (use Chrome to try and improve "luck"), close the page and reopen and maybe you'll see it then. Otherwise you'll just see the empty "box" where the error/snippet preview should be.

### Additional context
I tried calling the URL which Yoast also calls: DOMAIN/?type=1480321830&pageIdToCheck=5580&languageIdToCheck=1&additionalGetVars=
The response has no URI apparently: {"error":{"uriToCheck":"","statusCode":"-1"}}

### Technical info
* TYPO3 version: 8.7.27
* Yoast SEO version: 5.1.0

**Comment by ww-ysg** [comment]
Dear Team,

I encountered the same error using TYPO3 8.7.41 and Yoast SEO version 7.2.2.

Best Regards,
Yasin

**Comment by RinyVT** [comment]
I'm sorry this issue didn't receive any attention at the time. Due to the age of the issue, I'll close this for now.

I've tested this issue on TYPO3 9, 10 and 11 and this issue does not occur anymore. This probably has something to do with the way we do the generation of the frontend url now (which now a backend route and uses the SiteRouter) versus the old frontend type-url.

Unfortunately we do not support TYPO3 8 anymore, so this will not be fixed in version 7.x
