### ISSUE TITLE
Sitemap.xml results in 404 page using autoconf realurl

### ISSUE THREAD

**Issue by randomresult** [Yoast/Yoast-SEO-for-TYPO3#321]
* [ ] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

Installing version 5.1.0 in a TYPO3 8.7.30 Install.

When trying to access the www.domain.com/sitemap.xml it results in a 404 page. 
Using the index.php?type=1522073831 the sitemap is delivered.

Seems to work with manual configuring of realUrl.

### Technical info
* TYPO3 version: 8.7.30
* Yoast SEO version: 5.1.0

**Comment by haassie** [comment]
We don't provide auto configuration anymore as it did give errors on several installations. Best way is to do manual configuration. I updated the docs and should be published in a couple of minutes.
