### ISSUE TITLE
SnippetPreview not displayed on first page properties opening

### ISSUE THREAD

**Issue by helsner** [Yoast/Yoast-SEO-for-TYPO3#322]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
When editing the page properties the snippetpreview is not loaded/shown.
On frame reload or saving the preview gets properly displayed.
Also there's no issue with the preview in normal page module view.

Console log shows the following
![Bildschirmfoto 2020-01-16 um 11 12 33](https://user-images.githubusercontent.com/16156392/72526954-e3089980-3867-11ea-88af-c75deea44139.png)

### How can we reproduce this behavior?
1. edit page properties
2. switch to seo tab
3. -> missing snippetpreview

### Technical info
* TYPO3 version: v9 LTS
* Yoast SEO version: 5.1.x (latestes)
* Relevant extensions in case of a bug: -

**Comment by steffenf14** [comment]
might relate to or is the same as https://github.com/Yoast/Yoast-SEO-for-TYPO3/issues/340

**Comment by helsner** [comment]
This issue is still occurring to me in v10 LTS with v7 yoast version
Same error message and behavior in general.
On first call of the page properties the console error occurs and no preview is loading.
On frame reload or save the snippet get's loaded

Also no loading "bubbles" are shown on calling, while the tx_yoastseo_readability_analysis does show them and loads 
![Bildschirmfoto 2020-08-20 um 17 39 23](https://user-images.githubusercontent.com/16156392/90793536-21899980-e30c-11ea-9ea4-b1eb3d71e059.png)

**Comment by helsner** [comment]
FYI:
The frame reload/save have to be made when the SEO tab is selected.
If another tab is selected the probability that the preview works is very low (not 0, sometimes it works, but mostly not)

Same counts for the general page edit:
If you open the page and select SEO no preview is shown - the error happens
If you close and repopen the SEO tab is preselected and the preview is displayed

When you change that process to switching the tab to e.g. general, close the page and reopen the page the preview fails again.

**Comment by helsner** [comment]
Current state of debugging:
Concrete function that causes the issue:
https://github.com/Yoast/YoastSEO.js/blob/c18e31744fc03c36bef9e599a7da1ca6e0962ff2/src/stringProcessing/replaceDiacritics.js

Call of this function comes from here:
https://github.com/Yoast/yoast-components/blob/df888f1ca5918e01fbd0e62d0e64c1997afd82e4/composites/Plugin/SnippetPreview/components/SnippetPreview.js#L482


Additional reproduce info:
As already mentioned the issue occurs when you open the page properties and switch the tab to SEO.
However! the error does not occur when the "savesscores"-XHR has been called (which happens after a short amount of time)
When you switch after the call the preview works just fine.


This should be caused by the following:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/Resources/Public/JavaScript/plugin.js#L253
The issue is that the content is not loaded while updateContent is called.
updateContent triggers the reducer which sets isFetching: true, which is not correct.
Queuing should bring the solution
