### ISSUE TITLE
Snippet preview/score bar overlapping other functionality using the PageLayoutHeader hook

### ISSUE THREAD

**Issue by patrickbroens** [Yoast/Yoast-SEO-for-TYPO3#324]
The score bar on top of the snippet preview, rendered in the page module using the PageLayoutHeader hook, is having a negative margin. When adding other functionality to the PageLayoutHeader hook, above the score bar and snippet preview, the score bar is interfering with the other functionality, because it is forced up with the following CSS
```
.yoast-seo-score-bar {
    margin-top: -15px;
}
```
The negative margin should be removed here, so it does not overlap the other added functionality. Other functionality using the same hook should not be forced to add extra margins because of the Yoast SEO score bar.

### How can we reproduce this behavior?
1. Make some functionality using the PageLayoutHeader hook and make sure it is loaded before the Yoast page layout header. In CSS make sure the content of the outer container stays inside the container.
2. Check that the 'score-bar' is overlapping the container mentioned before

### Technical info
* TYPO3 version: 9.5
* Yoast SEO version: 5.1.1

**Comment by helsner** [comment]
I can confirm this issue.
In my case in v10 along with the blog extension it is overlapping the new blog meta overview.
This is very inconvenient as the blog extension is perfectly suited to be used along with yoast as a analysis tool
![Bildschirmfoto 2020-08-21 um 10 14 30](https://user-images.githubusercontent.com/16156392/90868736-89d18d00-e397-11ea-8f18-fa2e4ea8a721.png)
