### ISSUE TITLE
Fetching Typoscript settings for allowedDoktypes breaks adding new rootline fields

### ISSUE THREAD

**Issue by Mabahe** [Yoast/Yoast-SEO-for-TYPO3#327]
Added new rootline fields. Using typo3-console `database:updateschema` and `cache:flush` results in an exception `Unknown column 'tx_foo_bar' in 'field list'`.
Tracked this down to the call `YoastUtility::getAllowedDoktypes` from pages and pages_language_overlay TCA overrides. Fetching the TypoScriptConfiguration results in fetching the rootline which breaks for a missing database field.

Was already happy to have the typoscript setting only as fallback in https://github.com/Yoast/Yoast-SEO-for-TYPO3/commit/63a1ea8d5101dced6c91195d559c760686d33260 but with #299 it gets processed in any case again.

I suggest to add a feature flag, which is on by default, but could set to off.

### Technical info
* TYPO3 version: 8.7
* Yoast SEO version: 5.1.1

**Comment by saitho** [comment]
Same issue in 9.5.
