### ISSUE TITLE
10LTS broken UpgradeWizard

### ISSUE THREAD

**Issue by helsner** [Yoast/Yoast-SEO-for-TYPO3#330]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
When trying to upgrade to the newest 10LTS Version an issue occurs while using the upgrade wizard.
CanonicalFieldUpdate.php and SeoTitleUpdate.php extend the "AbstractUpdate.php" of the sysext:install which is not present.

### How can we reproduce this behavior?
1. install 10LTS with newest yoast
2. run through upgrade (in my case via typo3-console)
3. "vendor/bin/typo3cms upgrade:list" should already display the issue

### Screenshots

`Fatal error: Class 'TYPO3\CMS\Install\Updates\AbstractUpdate' not found in /Users/helsner/XXXX/typo3conf/ext/yoast_seo/Classes/Install/SeoTitleUpdate.php on line 26
`

### Technical info
* TYPO3 version: 10 LTS 
* Yoast SEO version: 6+
* Relevant extensions in case of a bug: sysext: install

**Comment by wowawebdesign** [comment]
I can confirm this issue.

**Comment by haassie** [comment]
Hi. This is now fixed in the just released version 6.0.1
