### ISSUE TITLE
Site crashed when I install Yoast SEO Premium Extension

### ISSUE THREAD

**Issue by prasun1519** [Yoast/Yoast-SEO-for-TYPO3#332]
Yes

* 
- [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).

* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

I have downloaded the Yoast Premium Typo3 extension and uploaded it to our extension directory. But after installing it our site crashed and getting error 

(1/1) Error
Call to a member function getPackagePath() on null

### Please describe what you expected to happen and why.
It should install the Yoast SEO Premium extension

### How can we reproduce this behavior?
1. 
2.
3.

### Screenshots
If applicable, add screenshots to help explain y
![Yoast SEO Error](https://user-images.githubusercontent.com/13601817/81473685-c977cd00-921d-11ea-91bc-26c4418fb036.png)
our problem.

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 9.5.14
* Yoast SEO version: Premium 3.0.1
* Relevant extensions in case of a bug:

**Comment by haassie** [comment]
For Yoast SEO Premium for TYPO3 support, best is to contact the support team at typo3support@yoast.com. If you send an email to that address, we will make sure you will receive an updated version of the extension to check this error.
