### ISSUE TITLE
Make Remark in HTML-sourcecode switchable

### ISSUE THREAD

**Issue by ZYZ64738** [Yoast/Yoast-SEO-for-TYPO3#333]
Becasue of security concerns it would be nice to give attackers as few information as possible.
So i wish to disable the HTML-Remark:

`<!-- This site is optimized with the Yoast SEO Premium for TYPO3 plugin - https://yoast.com/typo3-extensions-seo/ -->`

in the rendered HTML-Sourcecode without touching the php-code of the extension.

thx

**Comment by haassie** [comment]
Just like core we will keep this comment in the code. This kind of information is really low risk, so I see no real good reason to make this configurable.
