### ISSUE TITLE
Language translations don't overwrite default language settings

### ISSUE THREAD

**Issue by UebelBAM** [Yoast/Yoast-SEO-for-TYPO3#336]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
When setting the robots instructions on the default page, those settings will be used with every other language. Editing the page in another language and setting other robots instructions doesn't save the new settings and instructions from the default language will be used instead.

### Please describe what you expected to happen and why.
Expected behaviour would be to set different robot settings per page and per language. For example english page can be "noindex", while the german version can still be on "index".

### How can we reproduce this behavior?
1. Set robot instructions for default language. For example "Do not index this page in search engines" on. Save page.
2. Edit same page on another language. Set "Do not index this page in search engines" off.
3. Save page and reedit. New setting "Do not index this page in search engines" is not saved.

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version: 8.7.32
* Yoast SEO version: 6.0.1
* Relevant extensions in case of a bug:

**Comment by UebelBAM** [comment]
Found an error in the installation, not a bug. Sorry

**Comment by RinyVT** [comment]
Due to the date of this issue and the removal of CMS8 support (robots are now handled within TYPO3 core), I'll close this issue. Sorry that we did not fix this.

Feel free to open a new issue if you encounter more/other problems with the current version.
