### ISSUE TITLE
UpdateWizard CanonicalFieldUpdate is missing return true in function executeUpdate

### ISSUE THREAD

**Issue by mxpgmbh** [Yoast/Yoast-SEO-for-TYPO3#337]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

When upgrading Typo3 from 8 to 9, the UpdateWizard CanonicalFieldUpdate fails with the error messsage: 
```
Return value of YoastSeoForTypo3\YoastSeo\Install\CanonicalFieldUpdate::executeUpdate() must be of the type boolean, none returned
```

### Please describe what you expected to happen and why.

Update Wizards completes without error

### How can we reproduce this behavior?

1. Install Typo3 8 with Yoast
2. Update to Typo3 9
3. Run the CanonicalFieldUpdate Update Wizard

### Logs
If applicable, add logs to help explain your problem.

### Additional context
The problem is actually really simple. The function `executeUpdate` in `Classes/Install/CanonicalFieldUpdate.php` is missing a `return true` statement.

### Technical info
* TYPO3 version: 8 LTS to 9 LTS
* Yoast SEO version: 3.0.5 to 6.0.1
* Relevant extensions in case of a bug: Yoast

**Comment by infabo** [comment]
Can confirm.
