### ISSUE TITLE
Preview Content disapears after Tab switch

### ISSUE THREAD

**Issue by steffenf14** [Yoast/Yoast-SEO-for-TYPO3#340]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
example: a page with empty "seo title"
1. opening a page and the yoast snippet preview appears on top as expected.
2. opening the properties of this page and switching to the yoast seo tab, to view the preview. the preview will be empty.
3. closing page properties and reopening page properties with the yoast seo tab already preselected. Snippet Preview is not empty
4. switching tabs will now clear the preview again.

my guess is that the javascript in the page properties always triggers a refresh (if you switch tabs) and only uses the SEO Title field to regenerate the preview.
might be related to https://github.com/Yoast/Yoast-SEO-for-TYPO3/issues/322

### Please describe what you expected to happen and why.
I expact the same preview as on the Page Content module.

### How can we reproduce this behavior?
see description

### Additional context
Tested on 2 different pages with no relation to each other.

### Technical info
* TYPO3 version: 8 LTS and 9 LTS
* Yoast SEO version: 5.1.0 and 6.0.1
* Relevant extensions in case of a bug: content_defender, gridelements

**Comment by steffenf14** [comment]
Console does not throw any errors or warnings.

**Comment by darthnorman** [comment]
The whole preview part is broken, imo.. why don't you take the data from the database? And render it in fluid?
When getting all the data by an ajax call, most of the time it is more or less empty and I don't know why. The response is unable to obtain the title nor the description, although the page has the doktype = 0. When using another doktype, it takes the title from the root page - totally random to me.

**Comment by haassie** [comment]
@steffenf14 can you check if this is fixed with the latest released version? This should be fixed now.

**Comment by haassie** [comment]
@darthnorman We can't take the data from the database. There are a lot of possibilities to alter the title of the page. So we need to check the frontend. In the end: that is also what Google does. If it analyses and don't get a good result, we can check why that happens if you have a premium subscription.

**Comment by RinyVT** [comment]
Closing due to lack of feedback. This should be fixed in the latest versions.
If this issue still occurs, feel free to open a new issue.
