### ISSUE TITLE
DB-Compare still broken if database schema is not up to date

### ISSUE THREAD

**Issue by helhum** [Yoast/Yoast-SEO-for-TYPO3#350]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

https://github.com/TYPO3-Console/TYPO3-Console/issues/925
yoast_seo accesses the database when building TCA.
Since TCA is required to determine the database schema,
errors will occur, when the database schema isn't complete.

### Please describe what you expected to happen and why.

Building TCA should not access the database

### How can we reproduce this behavior?
1. Remove `alias` field from pages table
2. Do a DB compare in install tool

### Technical info

See: https://github.com/TYPO3-Console/TYPO3-Console/issues/925

**Comment by haassie** [comment]
Thanks for your report @helhum. Will check and fix ASAP.

**Comment by haassie** [comment]
Bugfix is in review. Meanwhile you can set `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['yoast_seo']['allowDoktypesFromTypoScript']` to `false` so this code will not be executed. As this is a breaking change, it will be released in v7
