### ISSUE TITLE
Cornerstone Help Link is not rendered (German, TYPO3 v9.5.20, Yoast SEO v7.0.0)

### ISSUE THREAD

**Issue by AMartinNo1** [Yoast/Yoast-SEO-for-TYPO3#362]
![image](https://user-images.githubusercontent.com/5464339/90028770-62553300-dcba-11ea-99f0-770817dfc367.png)

Switching to english and I can see the link:
![image](https://user-images.githubusercontent.com/5464339/90028864-7b5de400-dcba-11ea-8531-fdf6549c7ef2.png)

**Comment by haassie** [comment]
I changed this in the crowdin translation project and should be published I believe after a day. You need to update your languages in your installation to do so. Please let me know if the text is not updated in a few days.

**Comment by AMartinNo1** [comment]
Hi @haassie 
Thanks for the info. I am on vacation now and will check monday 28th.

**Comment by AMartinNo1** [comment]
@haassie Yes, updated it on my local instance and the german text does contain the link now.
