### ISSUE TITLE
Preview Snippet for page with access rights.

### ISSUE THREAD

**Issue by Megafry** [Yoast/Yoast-SEO-for-TYPO3#367]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
The Preview Snippet doesn't work when the page has access rights.

### Please describe what you expected to happen and why.
The Preview Snippet should add the preview parameter **simUser**
ex:  **?ADMCMD_simUser=27** [simulateUserGroup](https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php#L117)

### How can we reproduce this behavior?
1. Create a page
2. add access rights (for group)
3. go back to the Preview Snippet.
4. (The server was not able to access the page to analyse your content, When trying to fetch ..., a 403 status code was received. Please make sure your server can access the page.)

### Technical info
* TYPO3 version: 10.4.6
* Yoast SEO version: 7.0.0

**Comment by dahaupt** [comment]
@Megafry I just encountered this issue. What was the reason for closing it?

For now, I disabled the snippet preview via PageTS for affected pages. What about disabling it in general in case access rights are active (page field `fe_group` is not empty)? I guess those pages do not need any SEO optimization at all.
