### ISSUE TITLE
What is the URL path to the sitemap

### ISSUE THREAD

**Issue by toccamonium-fe** [Yoast/Yoast-SEO-for-TYPO3#370]
Hi,
I checked the documentation to figure out which URL I have to call to see the sitemap.xml created for my TYPO3 website version 9.5?

Found it, but it's not working > https://www.urban-living-hamburg.de/?type=1522073831

Thx
Florian

**Comment by haassie** [comment]
In TYPO3 v9, the sitemap is generated by the core and not by EXT:yoast. More info on this can be found on https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/XmlSitemap/Index.html.
