### ISSUE TITLE
Not compatible with php 7.3

### ISSUE THREAD

**Issue by dotpbn** [Yoast/Yoast-SEO-for-TYPO3#378]
Hi,

I need to install this extension for my Magento store, but it's not compatible with PHP 7.3. Anybody can fix this, please?

thanks

**Comment by haassie** [comment]
Hi @dotpbn . Thanks for your report. I think that you have the wrong repository though. This repository is for the Yoast SEO for **TYPO3** extension and not for Magento. The TYPO3 plugin works perfectly fine with PHP7.3.
