### ISSUE TITLE
Wrong previewPageId used in combinations with snippetPreview in records causes Exception

### ISSUE THREAD

**Issue by lkreitz** [Yoast/Yoast-SEO-for-TYPO3#387]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

I use the extension in a multi-language site in my own extension for records. I added the configuration to my extension according to the instructions from the extension manual (https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/7.0/en-us/Configuration/OtherPlugins/Index.html). So far everything works fine.

But when I want to locallize a record I some time get an error like this (example):
 #1521716622 TYPO3\CMS\Core\Exception\SiteNotFoundException
No site found in root line of page 13

After some research I can say, that the id given in the error is the id of the parent record. My research guides me to line 310 in the SnippetPreview.php file, where the previewPageId is overwritten with the id of the value of 'l10n_parent' in the recordArray, which is obviously the id of the parent record. That makes sense for pages but not for records, as there i use a id of an page with an plug-in als previewPageId.

### Please describe what you expected to happen and why.

In this case the previewPageId should not be overwritten by the parent record.

### How can we reproduce this behavior?
1. Add a record with an uid where no page with the same uid is available in the backend
2. Try to create an localized version of this record

### Technical info
* TYPO3 version: 10.4.9
* Yoast SEO version: 7.0.3
* Relevant extensions in case of a bug: other plugins/own extension

**Comment by markusmuellerw** [comment]
An other problem accours because of the following line (SnippetPreview.php, line 310):
`$previewPageId = $recordArray[$l18nPointer];` 

If the here determined previewPageId exists, a wrong Page will be analysed and previewed in the snippet.

**I'm not sure, wheater this line has any other use, but think it could simply be removed.**
