### ISSUE TITLE
Yoast blocks database update

### ISSUE THREAD

**Issue by ayacoo** [Yoast/Yoast-SEO-for-TYPO3#389]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

We have a custom extension that extends the pages table (TCA, SQL) and extends the addRootLineFields in the ext_localconf.php in one commit. So nothing special. Let us call the field "new_field".

In the Install Tool we should now be able to add the new fields, but the DB Analyzer returns a 500. (CLI DB Compare not tested)

`Unknown column 'new_field' in 'field list'`

The trigger is the following way

- yoast_seo extends pages.php via TCA, too
- This finally leads via Typoscript Config to Core RootlineUtility
- Core RootlineUtility executes sql with the new sql fields from addRootlineFields

Unfortunately, what I lack is a clever approach to prevent this from happening. Perhaps only a small workaround is needed here. I would not see it as a bug in yoast per se.

### Calls

[...]

at TYPO3\CMS\Extbase\Configuration\ConfigurationManager->getConfiguration('Settings', 'yoastseo')
in /var/www/html/public/typo3conf/ext/yoast_seo/Classes/Utility/YoastUtility.php line 198

at YoastSeoForTypo3\YoastSeo\Utility\YoastUtility::getTypoScriptConfiguration()
in /var/www/html/public/typo3conf/ext/yoast_seo/Classes/Utility/YoastUtility.php line 42

at YoastSeoForTypo3\YoastSeo\Utility\YoastUtility::getAllowedDoktypes(null, true)
in /var/www/html/public/typo3conf/ext/yoast_seo/Configuration/TCA/Overrides/pages.php line 163

at require('/var/www/html/public/typo3conf/ext/yoast_seo/Configuration/TCA/Overrides/pages.php')
in /var/www/html/public/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1708

at TYPO3\CMS\Core\Utility\ExtensionManagementUtility::buildBaseTcaFromSingleFiles()
in /var/www/html/public/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1662

![Download](https://user-images.githubusercontent.com/5963331/98671707-f041c800-2354-11eb-86fd-9aec716e25dd.png)

### How can we reproduce this behavior?
1. Add custom extension with a new field
2. Jup to the install tool
3. Analyze Database

### Technical info
* TYPO3 version: 9.5.22
* Yoast SEO version: 6.0.1
* Relevant extensions in case of a bug: Custom extension

**Comment by YKWeyer** [comment]
Hi @ayacoo ,

We experienced a similar problem and this workaround did the job for us: https://github.com/Yoast/Yoast-SEO-for-TYPO3/issues/350#issuecomment-655066952 : 

> Meanwhile you can set `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['yoast_seo']['allowDoktypesFromTypoScript']` to `false` so this code will not be executed.

According to the comment, updating YOAST to the v7 should help as well :)

**Comment by ayacoo** [comment]
Ah cool thanks for the info! Then my search was not enough. I will take care of an upgrade then :-)
