### ISSUE TITLE
Call to deprecated method in UserFunction

### ISSUE THREAD

**Issue by SZChimp** [Yoast/Yoast-SEO-for-TYPO3#399]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Accessing the sitemap.xml under domain.tld/sitemap.xml throws the following error:

> `Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Utility\ExtensionManagementUtility::siteRelPath() | Error thrown in file /<serverpath-to-webroot>/public/typo3conf/ext/yoast_seo/Classes/UserFunctions/XmlSitemap.php in line 92. Requested URL: https://www.domain.tld/sitemap.xml`

This leads increase load on the server the system resides on.

### Please describe what you expected to happen and why.

I expected the page to correctly show the sitemap.xml. This is needed for crawlers in SEO. 

The extension uses a method marked as deprecated since TYPO3 9: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-82899-ExtensionManagementUtilityMethods.html

Using the method stated in "Migration" does fix the issue:
```
use TYPO3\CMS\Core\Utility\PathUtility;
```
[...]
```
    protected function initialize()
    {
        $this->view = GeneralUtility::makeInstance(StandaloneView::class);
        $this->view->setFormat('xml');
        $this->view->getRequest()->setControllerExtensionName('yoast_seo');
        $this->privateResourcesPath = ExtensionManagementUtility::extPath('yoast_seo') . 'Resources/Private/';
        $this->publicResourcesPath = PathUtility::stripPathSitePrefix(ExtensionManagementUtility::extPath('yoast_seo')) . 'Resources/Public/';
        $this->templateFile = $this->privateResourcesPath . 'Templates/SitemapXml/Index.xml';
        $this->partialRootPaths = $this->getPartialRootPaths();
```
[...]

### How can we reproduce this behavior?
1. Install TYPO3 10.4.6, yoast_seo 7.0.7
2. Configure TypoScript Setup for robots.txt like this:
```
robots = PAGE
robots {
    typeNum = 201
    config {
        disableAllHeaderCode = 1
        additionalHeaders {
            10 {
                header = Content-type:text/plain
            }
        }
    }
    10 = TEXT
    10 {
        value (
# go away
User-agent: *
Disallow: /
        )
    }
}
robots.10.value (
Sitemap: https://www.domain.tld/sitemap.xml

User-agent: *
)
```
3. Call https://www.domain.tld/sitemap.xml

### Technical info
* TYPO3 version: 10.4.6
* Yoast SEO version: 7.0.0 (also tested with 7.0.7)

**Comment by haassie** [comment]
Hi @SZChimp, You are using the sitemap feature of Yoast SEO in a TYPO3 v10 installation? I highly suggest to use the core feature for this. The sitemap feature in Yoast SEO is used for TYPO3 v8, so yes it is right it uses deprecated features.

**Comment by SZChimp** [comment]
Hi @haassie , thanks for the reply. In this case the documentation should inform that the sitemap feature is not compatible in TYPO3 v10, I think.

**Comment by haassie** [comment]
That might be a good idea indeed. Let's keep this issue open to improve the documentation.
