### ISSUE TITLE
sourceComment is added if json+ld is not rendered

### ISSUE THREAD

**Issue by nostadt** [Yoast/Yoast-SEO-for-TYPO3#400]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

PR #382 added an empty check to stop rendering empty json+ld blobs. While this works the sourceComment as defined in https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/c5ef1d1d1f0cbef2628717c9e5f0dc99eb4c4e24/Classes/StructuredData/StructuredDataProviderManager.php#L49 is rendered anyway.

### Please describe what you expected to happen and why.

As json+ld is not provided by Yoast SEO I don't expect this comment.

### How can we reproduce this behavior?
1. Install v7.0.7
2. Deactivate structured data `config.structuredData.providers >`
3. Open FE in v9 LTS

### Technical info
* TYPO3 version: v9
* Yoast SEO version: v7.0.7

**Comment by haassie** [comment]
The comment has nothing to do with structured data, but indeed, it should ideally not be in this class.

**Comment by AMartinNo1** [comment]
I understand and respect the desire to show this information. Perhaps it can be added to the Standard TYPO3 HTML Comment?
