### ISSUE TITLE
Page edit "Yoast tab" missing (7.1.3)

### ISSUE THREAD

**Issue by Kayu84** [Yoast/Yoast-SEO-for-TYPO3#407]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
i upgraded an old typo3 v8 -> composer based v10 without yoast-seo-for-typo3/yoast_seo.

Now after the upgrade I wanted to use yoast again, but I was wondering where the yoast tab went.

The Yoast header for the page view is present, the dashboard works, all except for the Yoast tab for page editing.
i'm working with an admin account.

old v8 (page edit):
![image](https://user-images.githubusercontent.com/18236916/104851696-e3ae9280-58f6-11eb-822f-0c7854969888.png)

new v10 (page edit):
![image](https://user-images.githubusercontent.com/18236916/104851723-0c368c80-58f7-11eb-8d1c-59cb36b5b7d7.png)
![image](https://user-images.githubusercontent.com/18236916/104851829-9bdc3b00-58f7-11eb-888f-941014e21444.png)

new v10 (page overview):
![image](https://user-images.githubusercontent.com/18236916/104851845-bf06ea80-58f7-11eb-9944-69f2e63c1e0e.png)

### Please describe what you expected to happen and why.
I want to migrate the old keywords, focus keywords, descriptions etc, especially the yoast fields. But they are missing.

### Logs
There are no errors

### Technical info
* TYPO3 version: 10.4.7
* Yoast SEO version: 7.1.3
* Relevant extensions in case of a bug:
Powermail, News & Gridelements

**Comment by RinyVT** [comment]
Hi @Kayu84,

Is it possible you do not have the core extension EXT:seo ?
Because we also support v8 we cannot set this extension as a hard dependency, but this is needed for functionality in v9 and v10.

Please let me know if this fixes the issue.

**Comment by Kayu84** [comment]
Hi @RinyVT ,

thank you, this solves the problem.

I understand the problem with v8, but maybe there is an option to to add a version & extension check to give this essential hint on the yoast dashboard ?!
You should realy add an information if you cannot hard depend an extension.

maybe like this?
```
if (version_compare(TYPO3_version, '8.7.0', '>') {
    if (ExtensionManagementUtility::isLoaded('seo')) {
        ...
    }
}
```

**Comment by RinyVT** [comment]
That would indeed be a good idea!
We will soon release a minor upgrade for version 7 of this extension and this will be the last update for CMS8.
After that we will only support CMS9 and higher, at which we can set the seo extension as a hard dependency.

Thank you for the idea though, I will close this issue for now.
