### ISSUE TITLE
System behind htpasswd (Proxy) / snippet preview 401 / canonicals

### ISSUE THREAD

**Issue by Kayu84** [Yoast/Yoast-SEO-for-TYPO3#410]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
Got a Typo3 v10 Backend behind a proxy where the FE is reached under a different url (http s://website.com/).
So the Typo3 configuration sites is based on (preview) http s://admin-website.com/ & (backend) http s://admin-website.com/typo3, both secured with htpasswd. I cannot chang this behavior cause it's a customers system.

![image](https://user-images.githubusercontent.com/18236916/105610974-f7ed0680-5db2-11eb-8329-029f3a131213.png)

There is also an issue in the FE, the head-tags:
```
<link rel="canonical" href="http s:///admin-website.com/">
<link rel="alternate" hreflang="de-DE" href="http s:///admin-website.com/">
<link rel="alternate" hreflang="en-US" href="http s:///admin-website.com/en/">
```

### Please describe what you expected to happen and why.
I want to change the preview domain, i've found 2 files:
web\typo3conf\ext\yoast_seo\Classes\Backend\PageLayoutHeader.php
web\typo3conf\ext\yoast_seo\Classes\UserFunctions\SnippetPreview.php
both got a configuration:
```
protected $configuration = [
        'translations' => [
            'availableLocales' => [],
            'languageKeyToLocaleMapping' => []
        ],
        'menuActions' => [],
        'previewDomain' => null,
        'previewUrlTemplate' => '',
        'viewSettings' => []
    ];
```
i thought i could change the previewDomain to the non-credential open FE site:
'previewDomain' => 'http s://website.com/',

But without any effect.
Is there another location for configuration or can you give me a hint where i can place my modification?

### Technical info
* TYPO3 version: 10.4.7
* Yoast SEO version: 7.1.3
* Relevant extensions in case of a bug:
Powermail, News & Gridelements

**Comment by RinyVT** [comment]
Hi @Kayu84,

The configuration `previewDomain` you see is old configuration which has already been removed in the `master` branch.

In earlier versions of the extension we checked in the backend for the `previewDomain` which could be set through TSConfig.

Since version 9 and 10 came out, we made use of new routing mechanism and thus we do not check any `previewDomain` configuration.

What we DO have, is an available hook in where you can manipulate the uri to check:
https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/7.1/en-us/Configuration/Hooks/Index.html

The documentation says that it's for version 9, but it's also available for version 10.
Could you try this out and see if this fixes your issue?

**Comment by RinyVT** [comment]
I'm going to close this issue due to lack of feedback.
Feel free to open a new issue if this did not solve your problem! :)

**Comment by Kayu84** [comment]
Hello... i'm still working on this issue:
I've tried this "solution":
https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/7.1/en-us/Configuration/Hooks/Index.html

but it takes no effect.
i placed a file "YoastUrlToCheckHook.php" under extension/Classes/Hooks/
changed the Namespace:
`namespace Vendor\Extension\Hooks;`
set the url
`$urlToCheck = $params['https://new.test/'];`
added this line to "extension/ext_localconf.php"
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['YoastSeoForTypo3\YoastSeo\Service\UrlService']['urlToCheck'][] = Vendor\Extension\Hooks\YoastUrlToCheckHook::class . '->alterUrl';`
SC_OPTIONS can be checked in Backend

But the preview in backend still shows the domain from Site-Config.

And there is still the Problem, if this only changes the preview, that the Frontend generated codes like:
<link rel="canonical" href="https://domain/">
used the domain from site config.

The Problem is: This System runs under a local environment and a proxy-server will output this website under a different domain.

**Comment by Kayu84** [comment]
Works now: https://github.com/Yoast/Yoast-SEO-for-TYPO3/issues/441
