### ISSUE TITLE
German transitions words not recognized

### ISSUE THREAD

**Issue by KistersViewer** [Yoast/Yoast-SEO-for-TYPO3#413]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

we use your free Yoast plugIn in Typo3.
Unfortunately our impression is, that German transition words are not recognized.  Your plugin says "no transition words used at all", while we used several of them.
To us, this seems to be a BUG as in English it seems to work fine.

Is there a fix for it?

We are thinking about upgrading to Premium - but not as long the plugin confuses us more than it helps.

https://viewer.kisters.de/ich-suche-nach-1/nx-jt-viewer-visualisierung-dmu.html
https://github.com/Yoast/YoastSEO.js/blob/develop/src/researches/german/transitionWords.js

### Please describe what you expected to happen and why.
German transition words should get recognized. The plugin should report correct status - no complain, when used.

### How can we reproduce this behavior?
use sample text in screenshots

### Screenshots
![image](https://user-images.githubusercontent.com/78587247/107006127-fd722580-6790-11eb-8c17-04a09684e3a6.png)
![image](https://user-images.githubusercontent.com/78587247/107006358-4e821980-6791-11eb-828c-cbf3c41a5505.png)

### Technical info
* TYPO3 version: 9.5.22
* Yoast SEO version: 5.0.0
* Relevant extensions in case of a bug:

**Comment by RinyVT** [comment]
Hi @KistersViewer,

We are currently in the process of a new major version.
This should also include an update of all the Yoast-related (javascript) packages and the languages.
During testing, I will check if these updates fix these language issues.

**Comment by RinyVT** [comment]
Hi @KistersViewer,

We have just released a new version which contains a fix for the languages. Apparently, there was a problem with extracting the locale from the page content.
Could you check if this fixes your issue?
