### ISSUE TITLE
Error creating pages at root

### ISSUE THREAD

**Issue by thomasruta** [Yoast/Yoast-SEO-for-TYPO3#414]
Tested on new installation bootstap_package & introduction.
Creating an new rootpage at same level as Congratulations. 

```
(1/1) #1521716622 TYPO3\CMS\Core\Exception\SiteNotFoundException
No site found in root line of page 0

in /develop/rp-dev/private/releases/2019/Build/web/typo3/sysext/core/Classes/Site/SiteFinder.php line 135
            if (isset($this->mappingRootPageIdToIdentifier[(int)$pageInRootLine['uid']])) {
                return $this->sites[$this->mappingRootPageIdToIdentifier[(int)$pageInRootLine['uid']]];
            }
        }
        throw new SiteNotFoundException('No site found in root line of page ' . $pageId, 1521716622);
    }

    /**
     * @param bool $useCache
at TYPO3\CMS\Core\Site\SiteFinder->getSiteByPageId(0, array())
in /develop/rp-dev/private/releases/2019/Build/web/typo3conf/ext/yoast_seo/Classes/Service/UrlService.php line 69
        }

        if (version_compare(TYPO3_branch, '9.5', '>=')) {
            $siteFinder = GeneralUtility::makeInstance(SiteFinder::class);
            $site = $siteFinder->getSiteByPageId($finalPageIdToShow, $rootLine);
            if ($site instanceof Site) {
                $this->checkRouteEnhancers($site);

                $additionalQueryParams = [];

```

### Technical info
* TYPO3 version: 10.4.13
* Yoast SEO version: > 7.1
* Relevant extensions in case of a bug: yoast_seo

**Comment by RinyVT** [comment]
Hi @thomasruta,

By coincidence I installed a fresh v10 installation yesterday, with the introduction package and bootstrap package.
I noticed that the introduction package does not automatically add site configuration, could you check if there's site-configuration present in your installation?

**Comment by thomasruta** [comment]
No metter if auto config or manuell with yoast config.
The problem occures diu to rootpage id 0

**Comment by RinyVT** [comment]
@thomasruta 
You are right! This problem occurs when you add a page through the List module on root level.
We probably never saw the problem because of the most-used way of adding pages: dragging a page-type in the tree.

So, we'll have a look at this bug, in the meantime you can just drag a new page in the pagetree because that methods works.

**Comment by Kephson** [comment]
Hello,
I'm having the same bug today in TYPO3 version 10.4.14. Also Right-click -> New does not work to add pages on rootpage.

**Comment by RinyVT** [comment]
@thomasruta @Kephson,

Could you check if this issue still occurs in the latest 7.2.1?
We had to move the url-generation to within the ajax-call, and I think as a fortunate side-effect that this issue should also be resolved now.
I cannot reproduce it anymore at least.

**Comment by RinyVT** [comment]
Closing due to lack of feedback, feel free to reopen if this issue still exists.
