### ISSUE TITLE
does not define extension key in composer.json.

### ISSUE THREAD

**Issue by Christoph-Hofmann** [Yoast/Yoast-SEO-for-TYPO3#419]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

TYPO3 Extension Package "yoast-seo-for-typo3/yoast_seo", does not define extension key in composer.json.
Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by haassie** [comment]
Hi, this is already fixed with https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/417
