### ISSUE TITLE
Please add extension key in composer.json

### ISSUE THREAD

**Issue by j0nnybrav079** [Yoast/Yoast-SEO-for-TYPO3#421]
You need to add the extension key in composer.json. Please see:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra

If you want to, I could also create a pull request ;)

**Comment by haassie** [comment]
This is already done in master (see https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/composer.json#L63). Will be updated with next release.
