### ISSUE TITLE
Opening the YoastTab in the backend does not show the current bar status of the SEO title

### ISSUE THREAD

**Issue by schneider-horiba** [Yoast/Yoast-SEO-for-TYPO3#425]
* [ ] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
Opening the YoastTab in the backend does not show the current bar status of the SEO title. You see the behaviour here:
https://hcloud.horiba.de/index.php/s/tVhXOOQwC2N7toH

Once you click on an other tab such as General and go back to the Yoast Seo tab you see the right value in the statur bar of the SEO title.
https://hcloud.horiba.de/index.php/s/tVhXOOQwC2N7toH

### Please describe what you expected to happen and why.
The stauts bar of the SEO title should directly show the correct value. 

### How can we reproduce this behavior?
1. 
2.
3.

### Screenshots
https://hcloud.horiba.de/index.php/s/tVhXOOQwC2N7toH

### Logs
If applicable, add logs to help explain your problem.

### Technical info
* TYPO3 version:
* Yoast SEO version:
* Relevant extensions in case of a bug:

**Comment by schneider-horiba** [comment]
Hi,

I have updated the ticket with a link which is working for you.

Here it is again. https://hcloud.horiba.de/index.php/s/tVhXOOQwC2N7toH


Best regards

Markus Schneider
Global Digital Marketing
Sales Europe

HORIBA Europe GmbH
Hans-Mess-Straße 6
61440 Oberursel (Germany)
Office: +49 6172 1396-0   Ext: -172
Mobile: +49 173 3129268
Email: ***@***.******@***.***>

Von: Riny van Tiggelen ***@***.***>
Gesendet: Donnerstag, 10. Juni 2021 21:07
An: Yoast/Yoast-SEO-for-TYPO3 ***@***.***>
Cc: Markus Schneider ***@***.***>; Author ***@***.***>
Betreff: Re: [Yoast/Yoast-SEO-for-TYPO3] Opening the YoastTab in the backend does not show the current bar status of the SEO title (#425)


Hi,

As I'm not able to see the screenshots you provided (I'm getting a login screen), could you provide the information as requested under Technical info?
Or store the screenshots somewhere where they're visible to me? :)

Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fYoast%2fYoast%2dSEO%2dfor%2dTYPO3%2fissues%2f425%23issuecomment%2d858927718&umid=b43b806c-de25-4f50-805d-c1c23fa706c7&auth=b6f66d00f8195cc5198eee21f0dbabe6af0a3180-d8288a4c0ac1b7a738555002125b2ddbabf3cea0>, or unsubscribe<https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fAT36EMVITXGM6J23674NW7LTSEEM7ANCNFSM43XFEPFQ&umid=b43b806c-de25-4f50-805d-c1c23fa706c7&auth=b6f66d00f8195cc5198eee21f0dbabe6af0a3180-97754e57eb5b7a3f77727c4982b1bf846b863253>.

Als GmbH eingetragen im Handelsregister Bad Homburg v.d.H. HRB 9816, USt.ID-Nr. DE 114 165 789 Geschäftsführer: Dr. Hiroshi Nakamura, Dr. Robert Plank, Markus Bode, Takashi Nagano, Junichi Tajika, Ergin Cansiz.

**Comment by RinyVT** [comment]
@schneider-horiba 

I can see what you mean, if you open a page or record where the SEO tab is directly selected, the status bar is not being initialized properly.
I have add the `bug` label to this issue.
