### ISSUE TITLE
Kills custom Backend modules based on PageRenderer 

### ISSUE THREAD

**Issue by dmitryd** [Yoast/Yoast-SEO-for-TYPO3#428]
### Please describe what you expected to happen and why.

If there is a custom legacy backend module that uses PageRenderer, yoast_seo hooks will execute and try to append canonical URLs and other data to generated pages. These hooks use `$GLOBALS['TSFE']->cObj`, which does not exist in the BE context. Therefore an exception will be thrown.

We have this in a legacy v8 project.

### How can we reproduce this behavior?

Unfortunately you need an old BE module that uses PageRenderer.

### Technical info

The fix is pretty simple: use hooks to PageRenderer only in FE mode. These hooks are not needed in the BE mode anyway.

```diff
--- yoast_seo/ext_localconf.php
+++ yoast_seo/ext_localconf.php
@@ -1,12 +1,14 @@
 <?php
-$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms/layout/db_layout.php']['drawHeaderHook'][]
-    = \YoastSeoForTypo3\YoastSeo\Backend\PageLayoutHeader::class . '->render';
-$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-postProcess'][]
-    = \YoastSeoForTypo3\YoastSeo\StructuredData\StructuredDataProviderManager::class . '->render';
-$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-postProcess'][]
-    = \YoastSeoForTypo3\YoastSeo\Frontend\AdditionalPreviewData::class . '->render';
-$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['usePageCache'][]
-    = \YoastSeoForTypo3\YoastSeo\Frontend\UsePageCache::class;
+if (TYPO3_MODE === 'FE') {
+    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms/layout/db_layout.php']['drawHeaderHook'][]
+        = \YoastSeoForTypo3\YoastSeo\Backend\PageLayoutHeader::class . '->render';
+    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-postProcess'][]
+        = \YoastSeoForTypo3\YoastSeo\StructuredData\StructuredDataProviderManager::class . '->render';
+    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-postProcess'][]
+        = \YoastSeoForTypo3\YoastSeo\Frontend\AdditionalPreviewData::class . '->render';
+    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['usePageCache'][]
+        = \YoastSeoForTypo3\YoastSeo\Frontend\UsePageCache::class;
+}

 \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptConstants(
     'config.yoast_seo.fe_preview_type = '
@@ -27,7 +30,7 @@
     '<INCLUDE_TYPOSCRIPT: source="FILE: EXT:yoast_seo/Configuration/TypoScript/setup.typoscript">'
 );

-if (version_compare(TYPO3_branch, '9.5', '<')) {
+if (version_compare(TYPO3_branch, '9.5', '<') && TYPO3_MODE === 'FE') {
     \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScript(
         'YoastSeoCms8',
         'setup',
```

**Comment by RinyVT** [comment]
Hi Dimitry,

We are currently working on version 8 of the extension which will drop CMS8 support, so unfortunately this change will not be made in the v7 version as this is in high-priority bugfix right now.
I suggest you unset the hooks yourself and and re-load them in frontend-mode only.

I will test these changes for version 8 so from CMS9 and above the backend will only load the appropriate hooks.

Just a quick note, your change also removes the `cms/layout/db_layout.php` hook, which **is** needed in the backend.

**Comment by RinyVT** [comment]
I'm going to close this issue, in the new version 8.0 the hooks are only called in `FE` mode:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/ext_localconf.php#L5-L12
