### ISSUE TITLE
config.yoast_seo.enabled = 0 not working

### ISSUE THREAD

**Issue by masi** [Yoast/Yoast-SEO-for-TYPO3#440]
The documention tells me that I can disable the meta tags by a TypoScript configuration.

The cited snippet does not work. I also could not find any reference to the keyword "enabled" within the sources.

I assume that the check should have been in the class StructuredDataProviderManager. Has it been removed? Was it ever there?

**Comment by RinyVT** [comment]
Hi @masi,

It seems indeed that this was a setting from one of the old versions and has not been updated in the documentation.
The last time this was used, was in v3:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/v3.0.5/Classes/Frontend/PageRenderer/PageMetaRenderer.php#L36

If you want to "disable" the structured data you should be able to unset the providers within typoscript:
```
config.structuredData.providers >
```

**Comment by RinyVT** [comment]
Closing due to lack of feedback, feel free to open a new issue if this did not solve your problem.

**Comment by masi** [comment]
Well, yes. What you wrote worked for me. If the documentation has been updated all is fine.
