### ISSUE TITLE
#2 System behind htpasswd (Proxy) / snippet preview 401 / canonicals

### ISSUE THREAD

**Issue by Kayu84** [Yoast/Yoast-SEO-for-TYPO3#441]
Hello... i'm still working on this issue:
I've tried this "solution":
https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/7.1/en-us/Configuration/Hooks/Index.html

but it takes no effect.
i placed a file "YoastUrlToCheckHook.php" under extension/Classes/Hooks/
changed the Namespace:
`namespace Vendor\Extension\Hooks;`
set the url
`$urlToCheck = $params['https://new.test/'];`
added this line to "extension/ext_localconf.php"
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['YoastSeoForTypo3\YoastSeo\Service\UrlService']['urlToCheck'][] = Vendor\Extension\Hooks\YoastUrlToCheckHook::class . '->alterUrl';`
SC_OPTIONS can be checked in Backend

But the preview in backend still shows the domain from Site-Config.

And there is still the Problem, if this only changes the preview, that the Frontend generated codes like:
<link rel="canonical" href="https://domain/">
used the domain from site config.

The Problem is: This System runs under a local environment and a proxy-server will output this website under a different domain.

**Comment by RinyVT** [comment]
Hi @Kayu84,

Could you check if your hook works with the pull request mentioned above?
Unfortunately with the latest security fix the hook was moved to a different class, which meant hooks registered under `UrlService` no longer worked.

**Comment by Kayu84** [comment]
Hi @RinyVT,

Yeah, thanks... now it works like as expected. :)

**Comment by Kayu84** [comment]
and it must be:
$urlToCheck = 'https://new.test/';
