### ISSUE TITLE
Extension conflicts with cs_seo : Preview of title fails

### ISSUE THREAD

**Issue by M-arcus** [Yoast/Yoast-SEO-for-TYPO3#446]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

Installing the cs_seo and yoast_sep extension leads to a failure when loading the preview in the content elements

### Please describe what you expected to happen and why.

Preview should be loaded without failing

### How can we reproduce this behavior?
1. Install cs_seo
2. Install yoast_seo
3. Open a content-element and look for the preview

### Technical info
* TYPO3 version: 10.4.14
* Yoast SEO version: 7.2.1
* Relevant extensions in case of a bug: cs_seo

**Comment by M-arcus** [comment]
Workaround:

Put this in an ext_localconf.php of an extension that gets loaded after cs_seo and yoast_seo:

```
if (
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('cs_seo')
    && \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('yoast_seo')
) {
    unset($GLOBALS['TYPO3_CONF_VARS']['SYS']['formEngine']['nodeRegistry'][1514550050]);
}

```

It disables the preview from yoast_seo

**Comment by M-arcus** [comment]
The cause is the `'nodeName' => 'snippetPreview',` it conflicts with cs_seo's TCA `'snippetPreview'`

**Comment by RinyVT** [comment]
Hi @M-arcus,

Although we do not have `cs_seo` listed as a conflict within the composer.json or ext_emconf, I don't think both extensions are going to work side by side.
There's just too much overlap between the extensions.
Can I ask what you're trying to solve with `cs_seo` what cannot be done (or isn't done out of the box) by Yoast SEO? Or the other way around?

Especially the snippet preview and analyzing of content is something both extensions share, and I do not see a solution other than your solution which you can put in your own custom (site) extension.

Thank you for the issue raised, this may help people who also want to run both extensions side by side.

**Comment by M-arcus** [comment]
> Can I ask what you're trying to solve with cs_seo what cannot be done (or isn't done out of the box) by Yoast SEO? Or the other way around?  
The original typo3 installation was created with `cs_seo`, but the backend previews and checks are done with `yoast_seo`, as required by a client.
