### ISSUE TITLE
Prevent layout shifting on loading snippet preview

### ISSUE THREAD

**Issue by helsner** [Yoast/Yoast-SEO-for-TYPO3#452]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
It happens to me a lot that i missclick within the page module on content elements i want to edit as the snippet preview gets loaded and the layout is shifted.
This is only a small UX thing which can be pretty annoying at times.

### Please describe what you expected to happen and why.
Improvement:
Prevent layout shifting due to loading of the snippet preview.
I would guess this should be done by adding a fixed height to the whole preview section to prevent this.
I like the loading and the preview a lot, so good job there!

### How can we reproduce this behavior?
1. view page module
2. see the layout shift and changing the position of elements, their buttons etc.

### Technical info
* TYPO3 version: 10.4.21
* Yoast SEO version: 7.2.4

**Comment by helsner** [comment]
increasing the spinner margin to `margin: 100px auto;` does already a pretty good job.
Don't know if this would be enough of a solution but would be my suggest for the current time

**Comment by helsner** [comment]
@RinyVT what would be your opinion on this?
I could provide a patch if wanted.

**Comment by RinyVT** [comment]
Hi @helsner,

I just opened a pull request which adds a `min-height` to the snippet container, do you have a chance to test this and see if this meets your expectations?

**Comment by helsner** [comment]
Will try
