### ISSUE TITLE
[BUG] $previewService->getPreviewData parameter differs

### ISSUE THREAD

**Issue by ste101** [Yoast/Yoast-SEO-for-TYPO3#453]
In yoast_seo/Classes/UserFunctions/SnippetPreview.php
the function call is
```
$previewService->getPreviewData(
            $uriToCheck,
            (int)GeneralUtility::_GET('pageIdToCheck'),
            $GLOBALS['TSFE']->config['config'] ?? [],
            $GLOBALS['TSFE']->tmpl->setup['sitetitle'] ?? ''
        );
```
but the use parameters in yoast_seo/Classes/Service/PreviewService.php are only 
`getPreviewData($uriToCheck, $pageId)`

**Comment by RinyVT** [comment]
Hi @ste101,

I see what you mean, while updating the functionality for the title generation in this commit:
https://github.com/Yoast/Yoast-SEO-for-TYPO3/commit/67dee6b87ba693ca50104ab60c0d87e895725079

We did not adjust the CMS8 userfunction accordingly.
As we're currently working on a new major version which drops the CMS8 support, we will not fix this unfortunately.
If this prevents the preview from working in CMS8 (which I don't think so?), we could maybe have a look at high-priority bugfixing this for the soon-to-be older version.

I will close this issue for now.
