### ISSUE TITLE
Extension tries to include constants.typoscript - but there is no such file

### ISSUE THREAD

**Issue by twllndr** [Yoast/Yoast-SEO-for-TYPO3#458]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
After installation of yoast_seo 8.0.0 in a fresh TYPO3 11.5 installation you can see the following warning in the TypoScript-Object-Browser:

> Warning : File "EXT:yoast_seo/Configuration/TypoScript/constants.typoscript" was not found.

The file is included in ext_localconf.php - line 14-18. But there is no `constants.typoscript` in the given folder. So this include could/should be removed?

### Technical info
* TYPO3 version: 11.5
* Yoast SEO version: 8.0.0

**Comment by dennismetz** [comment]
Can confirm this issue.

**Comment by PhilippKuhlmay** [comment]
https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/feature/v8/ext_localconf.php#L17

**Comment by gessulatgessulat** [comment]
You are pointing to the file which is gonna load the constant file. But the file itself was removed.

https://github.com/Yoast/Yoast-SEO-for-TYPO3/commit/eb247c30aa84f1644b1a362554530c6d1d1c4080#diff-1f478101e291d808c3d58f196304313146eb159f3e74fe94239d2c55771f4f31
![YOAST gtilab removal commit](https://user-images.githubusercontent.com/15611815/140039559-50e6c2c3-4051-4c80-999e-b259631c383f.png)

And the TYPO3 Template Modul -> object Browser -> constants: shows an error.
![YOAST TS template browser constant error](https://user-images.githubusercontent.com/15611815/140039556-3dc66586-f339-4cd6-9605-f238480e620c.png)

**Comment by RinyVT** [comment]
This fix (removal of include) has just been released with version 8.1.0!

I'll close this issue now, feel free to open a new issue if you encounter more problems.

**Comment by gessulatgessulat** [comment]
RIP































Mit besten Grüßen
Best regards

Claus Gronemeier

-

CLAUS GRONEMEIER
Head of Digital

Tel (+49) 089.716771841 <089%20716771841>
Cell (+49) 0152.24189758 <015224189758>
Fax (+49) 089.7161849 <089%207161849>
Mail ***@***.***
---------------------------------------------------
Gessulat + Gessulat GmbH & Co. KG
Franz-Joseph-Strasse 23
D-80801 München

Büro Berlin:
Gessulat + Gessulat
Wulfsheinstrasse 10
D-10585 Berlin
---------------------------------------------------
www.gessulat-gessulat.de
---------------------------------------------------
*- Arbeitgeber der Zukunft 2022*
---------------------------------------------------

*- Top Arbeitgeber Mittelstand 2021 Focus Business*
---------------------------------------------------
* - kununu Top Company 2023*
---------------------------------------------------
Geschäftsführer: Stefan Gessulat
Sitz der Gesellschaft: München, Amtsgericht: München
Handelsregistereintrag: HRA 98814
Für diese Nachricht gilt:
http://www.gessulat-gessulat.de/impressum/


Am Mi., 24. Nov. 2021 um 15:56 Uhr schrieb Riny van Tiggelen <
***@***.***>:
