### ISSUE TITLE
Return value of YoastSeoForTypo3\YoastSeo\Form\Element\SnippetPreview::getPreviewPageId() must be of the type int, string returned

### ISSUE THREAD

**Issue by dennismetz** [Yoast/Yoast-SEO-for-TYPO3#459]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
If i try to open a record via list view in backend i got the following error message:
Return value of YoastSeoForTypo3\YoastSeo\Form\Element\SnippetPreview::getPreviewPageId() must be of the type int, string returned
The page id is returned as string like '123' and not int.

### Please describe what you expected to happen and why.
Open the record to edit.

### How can we reproduce this behavior?
1. Log into Backend
2. Change view to list view
3. Click on folder with (news) records
4. Open (news) record
5. Error occurs

### Screenshots
![grafik](https://user-images.githubusercontent.com/17856901/136987487-0a2d9e9d-a463-4df6-96bb-accaf9b4efae.png)

### Logs
If applicable, add logs to help explain your problem.

### Additional context
Problem solved (but not tested for other errors) when you change 
"return $previewPageId;" to "return (int)$previewPageId;"
in function: /Classes/Form/Element/SnippetPreview::getPreviewPageId

### Technical info
* TYPO3 version: 10.4.21
* Yoast SEO version: 8.0.0
* Relevant extensions in case of a bug:
* News: 8.6.0 
* yoast_news 2.1.2 (working under 10.4)

**Comment by dennismetz** [comment]
@cdaecke Yes, I can confirm that your fix works, thank you!

**Comment by RinyVT** [comment]
This fix has just been released with version 8.1.0. Thanks @cdaecke!

I'll close this issue, feel free to open a new issue if you encounter more problems.
