### ISSUE TITLE
Folder and Menu Separator visible in BreadcrumbList-schema 

### ISSUE THREAD

**Issue by Megafry** [Yoast/Yoast-SEO-for-TYPO3#460]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
By default the BreadcrumbList-schema does not exclude following doktypes: Menu Separator,Recycler & Folder

### Please describe what you expected to happen and why.
The BreadcrumbList-schema should exclude the following Doktypes by default:
`excludedDoktypes = 199,255,254` 

Folders are often used for meta-areas, but these are not a pages, so they should not be in the breadcrumb
This is the current result on Google
> https://www.mydomain.ch › -- Footer-Meta -- ▼

### Technical info
TYPO3 version: 10.4
Yoast SEO version: 8.0.0

**Comment by RinyVT** [comment]
Hi @Megafry,

Although I agree, this would be a breaking change as this would alter the functionality on existing websites using version 8.
For now, I have added a milestone for 9 on this issue and updated the documentation with a warning:
https://docs.typo3.org/p/yoast-seo-for-typo3/yoast_seo/master/en-us/Configuration/StructuredData/Index.html#excludeddoktypes
