### ISSUE TITLE
Raise PHP version

### ISSUE THREAD

**Issue by klodeckl** [Yoast/Yoast-SEO-for-TYPO3#461]
I wanted to install Yoast with TYPO3 11 via composer. It is not possible because Yoast has requirement PHP 7.2 and TYPO3 11 needs an least PHP 7.4. So please raise PHP version to 7.4 or 8. Thanks!

### Technical info
* TYPO3 version: 11
* Yoast SEO version: 8.0.0

**Comment by RinyVT** [comment]
Hi @klodeckl,

Introducing PHP8 also caused some warnings to be visible, and also made a few bugs visible.
I think I fixed it all in this PR: https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/463

Do you have the chance to test this branch?
Thanks in advance!

**Comment by spoonerWeb** [comment]
Installed the branch on my website with PHP 8.0 and `bootstrap_package`.
It works quite well, didn't see any error.

**Comment by klodeckl** [comment]
I installed the branch and get the following messages in the TYPO3 log file:

`Tue, 09 Nov 2021 20:32:47 +0000 [WARNING] request="9a92ec88ae0b7" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Undefined array key "tx_yoastseo_hide_snippet_preview" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/packages/yoast_seo/Classes/Utility/YoastUtility.php line 99
Tue, 09 Nov 2021 20:32:47 +0000 [WARNING] request="9a92ec88ae0b7" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Undefined array key "tx_yoastseo_cornerstone" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/packages/yoast_seo/Classes/Backend/PageLayoutHeader.php line 40
Tue, 09 Nov 2021 20:32:47 +0000 [WARNING] request="9a92ec88ae0b7" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Undefined array key "tx_yoastseo_focuskeyword" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/packages/yoast_seo/Classes/Backend/PageLayoutHeader.php line 42
Tue, 09 Nov 2021 20:32:47 +0000 [WARNING] request="9a92ec88ae0b7" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Undefined array key "tx_yoastseo_focuskeyword_synonyms" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/packages/yoast_seo/Classes/Backend/PageLayoutHeader.php line 43
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "defer" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2213
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "nomodule" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2214
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "integrity" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2215
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "crossorigin" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2216
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "defer" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2213
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "nomodule" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2214
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "integrity" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2215
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "crossorigin" in /var/www/vhosts/eckl-medien.de/helu.eckl-medien.de/public/typo3/sysext/core/Classes/Page/PageRenderer.php line 2216
Tue, 09 Nov 2021 20:32:49 +0000 [WARNING] request="6f9850de443a1" component="TYPO3.CMS.Frontend.Controller.TypoScriptFrontendController": $TSFE->set_no_cache() was triggered. Reason: no_cache has been set before the page was generated - safety check. Caching is disabled! - {"reason":"no_cache has been set before the page was generated - safety check"}`

**Comment by RinyVT** [comment]
@klodeckl Thanks for testing it out.
2 questions:
- Are you running the latest 11 version? The errors from the `PageRenderer` should be fixed: https://github.com/TYPO3/typo3/commit/a91fa19394aa60957f340ea996bcb172e0e874c4
- Does your database analyzer show missing fields? Particularly the Yoast fields, because the lines within `YoastUtility` where the errors are thrown, can only be reached with a valid page record and then those fields should always be available AFAIS

The last warning is known, the preview-functionality disables the cache while previewing the page on the frontend.

**Comment by klodeckl** [comment]
You’re right, I missed the database analyzer.
