### ISSUE TITLE
Sitemap missing categories

### ISSUE THREAD

**Issue by messtoo** [Yoast/Yoast-SEO-for-TYPO3#468]
Hello to everyone
There are missing categories in my sitemap and I can’t fix the problem. What path should I follow?
https://petsayfasi.com

**Comment by messtoo** [comment]
https://petsayfasi.com

**Comment by RinyVT** [comment]
Hi @messtoo,

Is your problem already resolved or is there a different problem?
When I look at the sitemap index:
https://petsayfasi.com/sitemap_index.xml
I follow the category link and this returns a list of categories:
https://petsayfasi.com/category-sitemap.xml
Are there categories missing there? If so, I think you'll have to search for differences between categories that are present and missing within the feed. I'm not really able to see the problem with the information you provided.

**Comment by RinyVT** [comment]
I'm going to close this issue due to lack of feedback, feel free to open a new issue if you're still experiencing problems.
