### ISSUE TITLE
EXT:yoast_seo_premium crawler stops crawling on news detail page (404)

### ISSUE THREAD

**Issue by christophlehmann** [Yoast/Yoast-SEO-for-TYPO3#486]
The crawler requests `/ajax/preview` of EXT:yoast_seo which returns a 404 on a news detail page (request news page without news parameter).

The preview action then returns 500 and the crawler stops crawling.

### Technical info
* TYPO3 version: ^10.4
* Yoast SEO version: 8.1.0
* Relevant extensions in case of a bug:

**Comment by RinyVT** [comment]
Hi @christophlehmann,

I have fixed this in the premium extension, this will be released as soon as possible.
I'll close this ticket for now, since this repository is used/meant for the free version of the extension.
Feel free to contact support@yoast.com for any future findings / questions.
