### ISSUE TITLE
EXT:yoast_seo_premium forces dashboard to be installed

### ISSUE THREAD

**Issue by georgringer** [Yoast/Yoast-SEO-for-TYPO3#500]
Services.yaml of ext: EXT:yoast_seo_premium sets up dashboards but this only works if dashboard is installed. either make it dashboard a requirement or move the configuration to `Services.php` see e.g. https://github.com/georgringer/doc/blob/master/Configuration/Services.php for inspiration

**Comment by RinyVT** [comment]
Thanks for the inspiration for a better fix!
This is included in the latest premium release 5.1.0.

I'll close this issue for now, please feel free to contact support@yoast.com (and/or open an issue here) for other premium related bugs.

**Comment by georgringer** [comment]
thanks for the fix. just as inspiration: maybe think about given access to people as I would have also added a PR ;)
