### ISSUE TITLE
add basic auth support

### ISSUE THREAD

**Issue by peterkraume** [Yoast/Yoast-SEO-for-TYPO3#53]
Currently it's not possible to use the TYPO3 extension on basic auth protected sites. This will result in this error message in the TYPO3 backend:
```
Loading the page content preview failed
503 Service Temporarily Unavailable
```

**Comment by haassie** [comment]
I just tried it to use it in a basic auth protected website and I don't have a problem and can use it. But my complete environment is protected so backend as well as frontend. 

If you take a look in the browser console, do you see any javascript error? Maybe on the network tab. The information is gathered by an AJAX-call. So your browser should be able to visit the frontend URL so if this call gets an error, you should be able to see it.

**Comment by Sebobo** [comment]
We also don't have an issue with that in our project.

**Comment by peterkraume** [comment]
I've tested this again with version 1.1.1 and currently everything works as expected. So I think this issue can be closed!
