### ISSUE TITLE
Support for TYPO3 v12

### ISSUE THREAD

**Issue by georgringer** [Yoast/Yoast-SEO-for-TYPO3#531]
Hey,

just wanted to ask if you plan to support TYPO3 v12 and if yes if you got a time plan for that?

thanks a lot!

**Comment by RinyVT** [comment]
Hi (everyone), sorry for the delay in the release.
We actually have a release ready to go but we're still ironing out some details between the free and premium version which makes it not possible to release the free version yet.
I hope to release the version week 23 or 24.

**Comment by kaystrobach** [comment]
Will the free version be compareable to the one for v11 or are you considering to reduce the features?

**Comment by RinyVT** [comment]
@kaystrobach Definitely not reducing the features of the free version! :)

**Comment by georgringer** [comment]
https://packagist.org/packages/yoast-seo-for-typo3/yoast_seo v9 seems to support v12. thanks!
