### ISSUE TITLE
Backend modules not showing in Access Lists in TYPO3 v12

### ISSUE THREAD

**Issue by webit-fernitz** [Yoast/Yoast-SEO-for-TYPO3#551]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
I wanted to grant access to YoastSEO submodules for backend users, but the submodules are not showing up in the Access List.

### Please describe what you expected to happen and why.
I expected the backend submodules to show up in the Access List so I could choose to grant access to users or user groups.
I expected this because YoastSEO registers three backend submodules and they are not restricted to admin / system maintainers.

### How can we reproduce this behavior?
1. Install YoastSEO for TYPO3 extension.
2. In backend module Backend Users, edit a backend user or user group.
3. Head to tab "Access Lists" and look for field "Modules".
4. The YoastSEO modules are not showing up in the list of modules.

### Additional context
I think the problem is related to the changes in how backend modules are registered that was introduced with TYPO3 v12: https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#backend-modules-configuration

More specifically, for the configuration option "access", a comma-separated list is no longer a viable input. Older versions of TYPO3 were allowing a comma-separated list of values. In v12, a single value should be given. The Yoast submodules are all being registered with "user,group" for the access option (https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/9.0.1/Configuration/Backend/Modules.php). In TYPO v12, this value is not being interpreted properly and the modules are therfor not showing up in the Access Lists. I have tried modyfing the Modules.php file locally to use "user" for the access option instead and then the modules were showing up. I am not sure what the best solution would be, since for older TYPO3 versions using only "user" as the option would probably mean a loss of functionality. Therefor I am reporting this as an issue to bring it to your attention.

### Technical info
* TYPO3 version: 12.4.4
* Yoast SEO version: 9.0.1

**Comment by tacoverdo** [comment]
Closed in favor of https://github.com/Yoast/Yoast-SEO-for-TYPO3/issues/545.
