### ISSUE TITLE
User Setting option does not appear in TYPO3 12

### ISSUE THREAD

**Issue by josefglatz** [Yoast/Yoast-SEO-for-TYPO3#555]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/Yoast-SEO-for-TYPO3/blob/master/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

User Setting option does not appear in TYPO3 12

**Comment by RinyVT** [comment]
Hi @josefglatz,

I do not see any problems with the field, see screenshot:

![Scherm­afbeelding 2023-09-12 om 18 34 37](https://github.com/Yoast/Yoast-SEO-for-TYPO3/assets/4457119/5884421b-2fb6-4482-bfe9-c9a066f57691)

Could you check the `showitem` in the `TYPO3_USER_SETTINGS`?

![Scherm­afbeelding 2023-09-12 om 18 35 42](https://github.com/Yoast/Yoast-SEO-for-TYPO3/assets/4457119/5dd2e1c6-f002-48e8-8f17-49604793ad4a)
