### ISSUE TITLE
SyntaxError: unterminated string literal

### ISSUE THREAD

**Issue by peterkraume** [Yoast/Yoast-SEO-for-TYPO3#57]
With TYPO3 backend language German the Yoast plugin shows only the spinner in the backend. In the browser console, the following error is shown:
`SyntaxError: unterminated string literal`

When you change the backend language to English, everything works as expected.

The problem probably occurs in wordpress-seo-de_DE.json.

**Comment by haassie** [comment]
This is fixed now in the master branch
