### ISSUE TITLE
v13 compatibility?

### ISSUE THREAD

**Issue by wowaTYPO3** [Yoast/Yoast-SEO-for-TYPO3#571]
I don't want to push, I just need to know for planning purposes: Do you plan to make the extension compatible for TYPO3 13?

**Comment by RinyVT** [comment]
Hi! We're absolutely planning on supporting TYPO3 13, already have some preparations ready.
We're hoping to release the supported version **before** TYPO3 13 LTS has been released.

**Comment by wowaTYPO3** [comment]
Cool, thanks for your quick reply. :)
