### ISSUE TITLE
Does not work with Flux / Fluidpages / Fluidcontent Extensions

### ISSUE THREAD

**Issue by bauermar** [Yoast/Yoast-SEO-for-TYPO3#60]
This Extension is not working with FED Extensions (https://fluidtypo3.org/)

**Comment by haassie** [comment]
Hi @bauermar. I'm not used to work with the FED extensions. Do you have more information about what doesn't work?

**Comment by schittly610** [comment]
With typo3 7.616 I get the following error:
Fatal error: Call to a member function getConfiguration() on a non-object in /var/www/.../typo3_src-7.6.16/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php on line 128

And with Typo3 8.7.1: Oops... Call to a member function getConfiguration() on null

The error only occurs if you try to access a page in the backend

**Comment by ColonelKilkenny** [comment]
Problem above can be fixed if $configurationManager is fetched like this in PageLayoutHeader->getAllowedDoktypes():

`
$objectManager = CMS\Core\Utility\GeneralUtility::makeInstance(CMS\Extbase\Object\ObjectManager::class);
        $configurationManager = $objectManager->get(CMS\Extbase\Configuration\ConfigurationManager::class);
`

Not sure if it is the correct way to do this and I don't think it fixes the extension completely. It just removes the error.

**Comment by schittly610** [comment]
@ColonelKilkenny thnx for the quick fix. Works for me.

**Comment by haassie** [comment]
Jukka,

Can you create a pull request for this? I will test it cross-TYPO3-version.

Richard

**Comment by bauermar** [comment]
This BUGFIX works for me too.
