### ISSUE TITLE
TYPO3 exception when saving Facebook/Twitter image

### ISSUE THREAD

**Issue by eddyast** [Yoast/Yoast-SEO-for-TYPO3#62]
Hello,
i tried to upload and save an image for Facebook and Twitter in the "Social" Tab in the Yoast SEO settings page. When i upload a new image to show on a Facebook/Twitter post i get after clicking on "Save" this TYPO3 exception:

Call to a member function addFile() on null

Error thrown in file
EXT:yoast_seo/Classes/Controller/ModuleController.php in line 285.

Uploading and saving the Facebook/Twitter image in the "Edit page properties" of my page works.

TYPO3 Version: 7.6.16
PHP Version: 7.0.15

**Comment by haassie** [comment]
The plugin is checking the default file storage to save the image. Do you have a default file storage set in your installation? Will add some checks around this function to prevent throwing this kind of errors.
