### ISSUE TITLE
SEO analysis doesn't work with gridelements

### ISSUE THREAD

**Issue by jvanderkroon** [Yoast/Yoast-SEO-for-TYPO3#63]
The analysis doesn't check content that is placed inside a gridelement.

**Comment by haassie** [comment]
Which version do you use? This should be fixed with commit 2b34740fb9a36c3839ec5c1528ae0839f89815c4. 

Otherwise, can you show me the output of index.php?id=85&type=1480321830&L=0 (insert right page id and language id) and a screenshot of the backend containing the right order?

**Comment by haassie** [comment]
Checked in several installations and it works for me. If you have more information, please reopen this issue. For now, I will close it.
