### ISSUE TITLE
Yoast SEO expects array

### ISSUE THREAD

**Issue by koningleeuw** [Yoast/Yoast-SEO-for-TYPO3#64]
When installing the Yoast SEO extension in TYPO3 8.7.1 it throws an error.
It looks like it's expecting an array, but is not served an array.

See the attached screenshot for more information.
 
![image](https://user-images.githubusercontent.com/29451748/27174066-101d1036-51bb-11e7-9210-a7aaaa7dccde.png)

**Comment by haassie** [comment]
Hi, I added an extra check if the extension can find configuration for the plugin. If not, it won't throw an error anymore. Main problem is a missing configuration in your installation I think. Can you please check if the TypoScript setting module.tx_yoastseo.settings.allowedDoktypes is containing several doktypes?
