### ISSUE TITLE
Broken Javascript in german translation file

### ISSUE THREAD

**Issue by sFreezer** [Yoast/Yoast-SEO-for-TYPO3#66]
In TYPO3 8.7.2, with v1.0, if I switch the language to German in the backend, I get a JavaScript error message `"Uncaught SyntaxError: Invalid or unexpected token"`, which is caused by multiple special chars (u2028) in [the translation file][de-json].

For example, see the first two occurences are after `"plug-in!`, here:
![special chars breaking JS](https://content.screencast.com/users/sfreezer/folders/Jing/media/a99710b4-2bef-4e2f-be97-833e6d17269f/2017-06-30_1818.png)

[de-json]: https://raw.githubusercontent.com/Yoast/Yoast-SEO-for-TYPO3/v1.0/Resources/Private/Language/wordpress-seo-de_DE.json

**Comment by haassie** [comment]
This is already fixed in commit 8c263086fbf9507570552d3d4bb9fffba2317619. Will be released soon!
