### ISSUE TITLE
Submit 1.0.1 to packagist

### ISSUE THREAD

**Issue by pgampe** [Yoast/Yoast-SEO-for-TYPO3#67]
And maybe you should setup the hook for packagist (see packagist documentation) such that the new versions are automatically published on packagist.

**Comment by arnoschoon** [comment]
Hi Philipp,

the release in TER is basically the same code base as v1.0, due to a typo in the ext_emconf this had to be released again. For the sake of readability I'll publish that to Packagist ;)

**Comment by arnoschoon** [comment]
https://github.com/Yoast/Yoast-SEO-for-TYPO3/tree/v1.0.1
https://packagist.org/packages/yoast-seo-for-typo3/yoast_seo

**Comment by pgampe** [comment]
Well, the primary reason for this was that the TER version worked, where the packagist version did not work.
Besides, if the packagist version is lower than the TER version, I will get warnings about not up-to-date extensions in my install ;) 

Thanks for updating to promptly.

**Comment by pgampe** [comment]
I just tested, it only works with the current git version, not with 1.0.1. With the released version, the loading indicator keeps showing and I get:

    Uncaught TYPO3 Exception: Class 'YoastSeoForTypo3\YoastSeo\Backend\PageLayoutHeader' not found
