### ISSUE TITLE
Add extension to the translation server

### ISSUE THREAD

**Issue by prathers** [Yoast/Yoast-SEO-for-TYPO3#68]
Please add the extension to the translation.typo3.org. You can post an issue here:
https://forge.typo3.org/projects/team-translation/issues

Great extension BTW 👍

**Comment by rvollebregt** [comment]
Issue created:
https://forge.typo3.org/issues/81874

**Comment by jokumer** [comment]
Please mark as solved. Added to translation server by Xavier Perseguers 15. july 2017
See https://translation.typo3.org/projects/TYPO3.ext.yoast_seo/

**Comment by haassie** [comment]
This is working correctly indeed.
