### ISSUE TITLE
Make it possible to check detailpage of a record

### ISSUE THREAD

**Issue by haassie** [Yoast/Yoast-SEO-for-TYPO3#70]
For extensions like news it should be possible to check the detailpage of a record. A lot of agencies use record-based plugins and it is the number 1 missing feature.

**Ideas:**
- For building the link to frontend, use the preview-link configuration

**Comment by haassie** [comment]
https://forge.typo3.org/issues/81297 is blocking ssing the preview link configuration.

**Comment by mbrodala** [comment]
@haassie Can you verify that change?

**Comment by NeoBlack** [comment]
Another missing feature in this area is not only the preview, also the possability to define canoncial URLs for news records, or much better, generate correct canonical URLs.

**Comment by stefanvar** [comment]
Hey, any news about this feature?

**Comment by haassie** [comment]
Hi. Yes. We just released the v2-beta for beta testers which will have this feature. If you like, I can send you information to join the beta phase.

**Comment by stefanvar** [comment]
Hi, this would be awesome! We are looking forward to this release and it's new features
