### ISSUE TITLE
Add Some Configuration Possibilities

### ISSUE THREAD

**Issue by cbuchli** [Yoast/Yoast-SEO-for-TYPO3#87]
A customer of ours - [zhdk.ch](https://www.zhdk.ch/) - would like to use the Plugin, but for it to work we need to have the following configuration options:

- the preview Domain must be configurable to be different than the domain record
- some features like the social need to be hidden in the backend because they don't work in our context

Pull Request is on its way.

**Comment by haassie** [comment]
This is now merged into master and will be shipped in version 1.2
