### ISSUE TITLE
Add support for hreflang

### ISSUE THREAD

**Issue by atimmer** [Yoast/Yoast-SEO-for-TYPO3#9]
Because multilingual is a built-in part of TYPO3 it might be a good idea to include hreflang in the first version. I've discussed this with @arnoschoon and it looks like it isn't that much work to add a simple list of `<link rel="alternate" href="...">` inside the head.

https://yoast.com/hreflang-ultimate-guide/

**Comment by haassie** [comment]
This is done by core now.
