### ISSUE TITLE
[BUG] Image fields for twitter and facebook not FAL field in edit modul

### ISSUE THREAD

**Issue by NeoBlack** [Yoast/Yoast-SEO-for-TYPO3#91]
The image fields for twitter and facebook are FAL fields in page record context, but simple upload fields if I edit it via the edit icon in the preview of the page module (own edit module).

So why? anyway, upload in this module does not work, a FAL relation is not created.

**Comment by haassie** [comment]
Hi @NeoBlack . We are working on rewriting the fields by using the FormEngine. But the image upload doesn't work for you? Here it is working and it is creating FAL relations. The only thing is that it is done manually and not the most future-proof solution.

**Comment by haassie** [comment]
This issue is linked to #76. Further development / information will be gathered on that issue.
