### ISSUE TITLE
[FEATURE] Configure pre/post texts and/or use stdWrap

### ISSUE THREAD

**Issue by NeoBlack** [Yoast/Yoast-SEO-for-TYPO3#92]
It would be nice to configure pre/post texts for title field or: use stdWrap for all fields, which give you the maximum flexibility. 

Example: the customer want a title tag in this form: ```<title>##PAGE_TITLE## | My Company Inc.</title>``` the Text: ```| My Company Inc``` should be appended automatic to all page titles.
The feature should be usable for all fields, so I guess using stdWrap would solve the problem for any use cases.

**Comment by sfsmfc** [comment]
This can easily be done, if you make your own partial, add a condition for the appended/prepended text and add the text in typoscript.

**Comment by sfsmfc** [comment]
Done in https://github.com/Yoast/Yoast-SEO-for-TYPO3/pull/98

**Comment by haassie** [comment]
Released with merging PR #102
