### ISSUE TITLE
SEO Yoast and tx_news

### ISSUE THREAD

**Issue by bandanh** [Yoast/Yoast-SEO-for-TYPO3#93]
Is it possible or planed to integrate SEO Yoast into tx_news or has this to be done from the tx_news Side?

**Comment by haassie** [comment]
Hi. The possibility to analyse TYPO3-records (like tx_news) is planned for the next major version. I hope I can give you a date of release of version 2 within a couple of days.

**Comment by haassie** [comment]
For further information, please check #70.

**Comment by bandanh** [comment]
Nice to hear that - thank you for this extension :-D
